frontend/components.js
public/css/styles.css

Simple footer

---

README.md
package.json

Minor quality of life improvement :)

Add dev npm script

---

frontend/components.js

- separate links in footer just by space
- target_blank on links
- should fix VL-logo appearance

Tweak footer

---

frontend/actions.js
test/test.js
wallet/address.js
wallet/cardano-wallet.js

chrome responsiveness and speedup

async lib for addresses generation

---

frontend/components.js
wallet/cardano-wallet.js

@ppershing  review to #38 that was not fixed before merging

fix: tooltip hiding timeout clearing, simplify getChangeAddress

---

package.json
yarn.lock

We talked about this a while back, everyone seemed to be fine with forcing prettier project-wide, so here it is :)

Force prettier on staged files

---

frontend/components.js
public_landing_page/index.html

The only relevant change is in footer text (rest is prettier autofix) - the emojis did not display on every system a the grammar was dubious either way, switched to a more conservative 'Developed by Vacuumlabs'.

Change footer text

---

package.json
server/blockchainExplorerProxy.js
server/transactionSubmitter.js
test/mock.js
test/test.js
wallet/helpers/pbkdf2.js
wallet/helpers/request.js
wallet/mnemonic.js
wallet/transaction.js

Everything autofixed with `yarn fix` (and checked with pre-commit hook).
Merge sometime when no-one has too much work unmerged in their feature-branches.

Prettier everything

---

public_wallet_app/css/styles.css

fix: render navbar over page content

---

frontend/actions.js
frontend/components.js
frontend/translations.js
frontend/validators.js
wallet/address.js

I made the suggested fixes mentioned in https://github.com/vacuumlabs/cardano/pull/55 and a small refactor of some functions in address.js which we talked about a while ago.

refactor address.js and input validation

---

frontend/components.js
public_wallet_app/css/styles.css

polish disclaimer on mobile devices

---

frontend/actions.js
frontend/components.js
public_wallet_app/css/styles.css

Success message shows for couple seconds, then fades out, form is cleared.
Error stays until something in the form is modified, form stays filled with previous address/amount.

Refetch  loading and send response UX

---

public_wallet_app/css/styles.css

Change width so that on browsers with fatter font the whole address is still visible.

Width to 1200

---

frontend/components.js
public_wallet_app/css/styles.css

Styling of confirmation dialog, more in tune with the overall page design

Send ADA confirmation styling

---

frontend/actions.js
frontend/components.js
frontend/printAda.js
frontend/translations.js
frontend/validators.js

refactor amount handling

---

frontend/components.js
public_wallet_app/css/styles.css

closes #78 
put on hold until content to github wiki is added

Add help/ FAQ section to menu

---

frontend/walletApp.js

This is a fix to issue #89 
I think it worked previously but it was probably with the old routing. I also found out that "currentTab" in state is not used so I deleted it.

tabs now switch when back button is pressed

---

package.json
server/index.js
yarn.lock

It will compres files before sending them to the browser.

Add compression to the server

---

wallet/cardano-trezor-crypto-provider.js

Derivation of multiple addresses at once was removed from trezor so now we have to ask addresses one by one and it means more popups. The popups should be fixed in next version of connect from trezor.
Also small changes was to the interface for signing transactions.

Refactor code based on change in trezor connect

---

frontend/components.js
public_wallet_app/css/styles.css

I moved error message below the amount input. Also on mobile devices is total amount moved below the input.
In this PR is also fix for showing total amount for invalid send amount.

Improve formating of validation error on mobile devices

---

frontend/components/common/navbar/navbarAuth.js
frontend/components/pages/dashboard/transactionHistory.js
public_wallet_app/css/styles.css

Balance is hidden from top navbar on mobile
Transaction history has changed columns order (amount is now before tx id)
Ada sign is smaller on mobile

Change transaction history and balance view

---

frontend/validators.js
test/tests/mnemonic.js
wallet/cardano-mnemonic-crypto-provider.js
wallet/mnemonic.js

fix paper wallet passphrase validation, fix paper wallet mnemonic test

---

.circleci/config.yml
README.md
app/frontend/wallet/blockchain-explorer.js
app/package.json
app/yarn.lock
package.json
server/transactionSubmitter.js
yarn.lock

Continuous integration

---

server/statsPage.js

Improve stats formatting

---

app/frontend/components/common/addressDetailDialog.js
app/frontend/libs/qrious.js

closes #139 
as normal scanners can read blockchain explorer's QRs, ad copy the addresss, we do not implement own html5 web RTC scanner, just generate and show QR for address

QR in address detail

---

app/frontend/actions.js
app/frontend/components/common/balance.js
app/frontend/components/common/footer.js
app/frontend/components/pages/sendAda/sendAdaPage.js
app/frontend/components/pages/txHistory/transactionHistory.js
app/frontend/components/pages/txHistory/txHistoryPage.js
app/frontend/helpers/getConversionRates.js
app/frontend/helpers/printConversionRates.js
app/public/css/styles.css

closes #199
getting conversion rates from [CoinGecko](https://www.coingecko.com)

show dollar/euro equivalent

---

app/frontend/components/common/navbar/navbarAuth.js
app/frontend/components/common/navbar/navbarUnauth.js
app/package.json
app/public/css/styles.css
landing_page/index.html
server/helpers/loadFrontendConfig.js

Closes https://github.com/vacuumlabs/adalite/issues/204.
I used inline styles for styling the version number on landing page, because i didn't know, where to put them.

Remove alpha

---

app/public/css/styles.css

closes #222 
There wasn't enough room to increase navbars z-index by 1

Fix z-indexes

---

app/frontend/components/common/footer.js

Closes https://github.com/vacuumlabs/adalite/issues/230

add link to telegram to footer

---

app/frontend/wallet/cardano-trezor-crypto-provider.js

don't display public key on trezor when exporting it

---

app/frontend/helpers/printConversionRates.js

Closes https://github.com/vacuumlabs/adalite/issues/226

add commas to fiat amounts, to make them more readable

---

app/frontend/components/pages/login/aboutOverlay.js
app/public/css/styles.css

Closes https://github.com/vacuumlabs/adalite/issues/232.

update disclaimer text

---

app/public/css/styles.css

Closes https://github.com/vacuumlabs/adalite/issues/235

make navbar button clickable from bottom of navigation

---

app/frontend/components/common/footer.js
app/public/css/styles.css
package.json

closes #234 
Footer sticks to bottom of page
Twitter link now 'Twitter'
Social media link bigger- no longer in `<small>`
Conversion rates line 15% smaller and only visible when on history page

Fix footer style

---

package.json
server/middlewares/stats.js
server/statsPage.js
yarn.lock

I don't know hot to test this on production, though :/ 
I believe host should be 'https://adalite.io/', but I don't know for sure.
@refi93 any ideas? 
Also another approach could be to use environment variables, and don't count usage if the app is running in dev mode.

Only add usage from adalite.com

---

app/frontend/components/common/addressDetailDialog.js
app/frontend/components/common/modal.js
app/frontend/components/pages/login/aboutOverlay.js
app/frontend/components/pages/login/demoWalletWarningDialog.js
app/frontend/components/pages/login/generateMnemonicDialog.js
app/frontend/components/pages/login/keyFileAuth.js
app/frontend/components/pages/login/loginPage.js
app/frontend/components/pages/login/logoutNotification.js
app/frontend/components/pages/sendAda/confirmTransactionDialog.js
app/frontend/components/pages/sendAda/sendAdaPage.js
app/public/css/styles.css

Created a general Modal component to make code more clear and adding Modals easier.
Refactored every component using css class 'overlay' to use Modal, except `LoadingOverlay', because it's too different from a typical modal.

refactor overlay into general Modal component

---

.release-it.json
README.md
RELEASES.md
package.json
yarn.lock

Added tutorial file containing steps on how to operate release it and setup GPG keys, tag signing was added over the weekend by the devs of release-it .

Release it setup

---

RELEASES.md

Improvements to RELEASES.md

---

app/frontend/actions.js
app/frontend/components/pages/sendAda/confirmTransactionDialog.js
app/frontend/wallet/blockchain-explorer.js
app/frontend/wallet/cardano-wallet.js
app/public/css/styles.css
app/tests/src/cardano-wallet.js

UX: Instead of showing a modal dialog, show an inline spinner (same as in calculate fee) and display a transparent overlay to disable UI interaction.

Disable overlay over transaction screen

---

app/frontend/actions.js
app/frontend/components/common/navbar/navbarUnauth.js
app/frontend/components/pages/login/loginPage.js
app/frontend/components/pages/login/mnemonicAuth.js
app/frontend/helpers/isLeftClick.js

https://github.com/vacuumlabs/adalite/issues/270

Adding create wallet button to the toolbar

---

app/public/css/styles.css

Closes #284 
Adjusted main brand colors from new design, added `primary & outline` buttons in various widths and removed old buttons that will need to be re-written anyway, no need to bloat the css file imo right now.

Add basic button styling

---

app/public/css/styles.css

Closes #286 
Defined colors & typography, moved all to the bottom of the stylesheet file

Define colors & normalize

---

app/frontend/components/common/alert.js
app/public/css/styles.css

Closes #294 
Created & styled Alert component in `positive, warning & negative` variations to be re-used across the webpage. Colors will be adjusted after merging the color defining PR.

Create separate Alert

---

app/frontend/components/pages/login/demoWalletWarningDialog.js
app/public/css/styles.css

Closes #298 
Added content as in the design, this PR is dependant on PR #292 where all the styling that will be re-used in these kinds of modals is. Also removed obsolete styling (typo rebased from `design-2.0` and modal styles will be rebased from `style-modals`). Added `Alert` component.

Demo wallet modal

---

app/frontend/components/pages/login/generateMnemonicDialog.js
app/public/css/styles.css

Closes #266 
The close button will be kept (it's missing from the design now).

Create New Wallet modal

---

app/public/css/styles.css

Add new info type to Alert

---

app/frontend/components/pages/login/loginPage.js
app/frontend/components/pages/login/loginPageSidebar.js
app/public/css/styles.css

Closes #272 
Created `loginPageSidebar` component that handles the content displayed right to the access method card. Created main login page layout - left the access card inners intact so we have manageable PR sizes. Used the new type of `info Alert` - this has already a PR so after rebasing will work as expected. Also added basic styles for `.card`.

Style sidebar

---

app/public/css/styles.css

Closes #305 
Removed old variables from the start of the file, kept only the `width, transition-easing & transition-time` and refactored the new styles to use the new variables. `width` also changed to `1288px` as in the new design.

Cleanup old style variables

---

app/public/css/styles.css

Removed duplicate `.card` & `main page` styles after rebasing multiple PRs

Removed duplicate .card & main page styles

---

app/frontend/components/common/balance.js
app/frontend/components/pages/txHistory/transactionHistory.js
app/public/css/styles.css

Transactions component

---

app/frontend/components/common/navbar/navbarAuth.js
app/frontend/components/common/navbar/navbarUnauth.js
app/public/assets/logout_symbol.svg
app/public/assets/logout_symbol_active.svg
app/public/css/styles.css

Style logged-in navbar

---

app/frontend/actions.js
app/frontend/components/pages/login/mnemonicAuth.js
app/frontend/store.js
app/public/css/styles.css

Login card content - mnemonic

---

app/frontend/components/pages/login/keyFileAuth.js
app/public/css/styles.css

Login card content - Key file

---

app/frontend/components/pages/login/hardwareAuth.js
app/public/css/styles.css

Closes #267 
Removed the `TrezorComingSoon` component as I suppose this has been implemented before the support for `Trezor T` has been rolled out and it's not needed now.

Login card content - hardware wallet

---

app/public/css/styles.css

Mobile footer

---

app/frontend/components/common/modal.js
app/frontend/components/common/tag.js
app/frontend/components/pages/exportWallet/exportCard.js
app/frontend/components/pages/exportWallet/exportWalletPage.js
app/frontend/components/pages/login/loginPage.js
app/frontend/components/pages/txHistory/txHistoryPage.js
app/frontend/components/router.js
app/public/assets/documents_icon.svg
app/public/assets/eye_icon.svg
app/public/assets/lose_icon.svg
app/public/css/styles.css

Closes #328
Styled dashboard export card, full page export card.
Refactored `Modal & LoginPage` components to use the `Tag` component.
Refactored the `padding-top: 136px` used on modal cards to `padding-bottom: 136px` for `.navbar` as all the pages have a `136px` wide gap between the `navbar` and the actual page content.

Style Export json cards

---

app/public/css/styles.css

Closes #334 
Should wait for PR #329 for merge of `Tag` component and also waiting on approval of copy (the desktop version has the text `I understand, continue to the demo wallet` in the `Access demo wallet` modal and the mobile version has `Continue to the demo wallet` - waiting whether both version will have the same text).

Mobile Modals

---

app/public/css/styles.css

Mobile Main layout

---

app/frontend/components/pages/login/logoutNotification.js
app/public/css/styles.css

Style LogoutNotification

---

app/frontend/components/pages/txHistory/txHistoryPage.js
app/public/css/styles.css

Closes #352 
Should have the `Send ADA & My Addresses` components as well.

Dashboard layout

---

app/public/css/styles.css

Mobile Export

---

app/frontend/components/common/navbar/navbarAuth.js
app/frontend/components/common/navbar/navbarUnauth.js
app/public/css/styles.css

Closes #338 
Changed navbar link colors (changed after the `navbar` became a symbol in Sketch - changed to a darker grey color)

Mobile navbar

---

app/public/css/styles.css

Mobile login card - initial

---

app/frontend/components/pages/login/loginPage.js
app/public/assets/dropdown_caret.svg
app/public/css/styles.css

Mobile Login tabs

---

app/public/css/styles.css

Mobile Addresses

---

app/frontend/actions.js
app/frontend/translations.js

This should notify users that they have network problems, so they don't get scared with a generic failure message

add error message to wallet initialization error

---

app/frontend/actions.js
app/frontend/components/common/navbar/navbarAuth.js
app/frontend/components/pages/login/mnemonicAuth.js
app/frontend/components/pages/receiveAda/myAddresses.js
app/frontend/components/pages/txHistory/txHistoryPage.js
app/frontend/components/router.js
app/public/css/styles.css

Closes #354 && #371 
Should wait for PRs for `My Addresses & Send ADA` to implement their mobile versions and then rebase to this PR.

Mobile Dashboard layout

---

app/public/css/styles.css

Tablet screens: Initial login, Welcome to Adalite, Not-logged in navbar, footer and related small component.
Also added bg-color for `body` as it was missing

Tablet Welcome modal & initial screen

---

app/frontend/components/pages/txHistory/txHistoryPage.js
app/public/css/styles.css

Tablet Dashboard

---

app/frontend/components/pages/receiveAda/myAddresses.js
app/frontend/components/pages/txHistory/transactionHistory.js
app/public/css/styles.css

Transactions & Addresses scrollable

---

app/public/css/styles.css

Closes #390 
Able to select mnemonic by a single click in the Create new wallet modal now.

Added styling for one-click selectability

---

app/frontend/components/pages/login/welcome.js
app/public/css/styles.css

Closes #386 
A few unrelated changes as well mostly regarding formatting due to changing to VSCode.

Welcome to AdaLite with fixed footer

---

app/frontend/components/common/addressDetailDialog.js
app/frontend/components/common/copyOnClick.js
app/frontend/components/pages/receiveAda/addressItem.js
app/public/css/styles.css

Closes #385 
One design change that's not in Abstract - the `QR Code` label got removed as it served no purpose.

Address detail modal (feedback)

---

app/frontend/components/common/navbar/navbarAuth.js
app/frontend/components/pages/login/demoWalletWarningDialog.js
app/frontend/components/pages/login/generateMnemonicDialog.js
app/frontend/components/pages/login/loginPageSidebar.js
app/public/css/styles.css

Closes #376 
Tooltips on balance -> created separate issue #379

Visual fixes from meeting

---

app/frontend/components/common/footer.js

Please check whether the donation address is the correct one

ADA donation address

---

app/frontend/actions.js
app/frontend/components/common/addressDetailDialog.js
app/frontend/components/common/balance.js
app/frontend/components/pages/login/generateMnemonicDialog.js
app/frontend/components/pages/receiveAda/addressItem.js
app/frontend/components/pages/sendAda/rawTransactionModal.js
app/frontend/components/pages/sendAda/sendAdaPage.js
app/public/css/styles.css

Testing feedback

---

app/frontend/components/common/navbar/navbarUnauth.js
app/frontend/components/pages/login/mnemonicAuth.js
app/public/css/styles.css

Closes #402 
Relocated the `Create New Wallet` functionality from the navigation to the Mnemonic login page.

Relocate Create new wallet functionality

---

app/frontend/components/pages/receiveAda/addressItem.js
app/public/css/styles.css

address numbers added

---

app/frontend/actions.js
app/frontend/components/pages/login/generateMnemonicDialog.js

generated mnemonic autocopy disabled & unlock button glitch fixed

---

app/frontend/components/pages/login/loginPage.js
app/frontend/components/pages/login/loginPageSidebar.js
app/public/css/styles.css

hw-wallet refactor

---

app/public/css/styles.css

overflow-y: scroll on modal-body is probably a mistake

hide scrollbar in modals if not needed

---

app/frontend/actions.js

address verification button reappear after verification

---

app/frontend/actions.js
app/frontend/components/pages/login/mnemonicAuth.js
app/frontend/helpers/sanitizeMnemonic.js
app/frontend/store.js
app/frontend/wallet/mnemonic.js

sanitize mnemonic added

---

app/frontend/actions.js

verify address error handle

---

app/frontend/actions.js
app/frontend/components/app.js
app/frontend/components/common/navbar/navbarAuth.js
app/frontend/components/common/navbar/navbarUnauth.js
app/frontend/components/common/welcome.js
app/frontend/components/pages/login/loginPage.js
app/frontend/store.js
server/helpers/loadConfig.js

Add about navbar link to all pages

---

.env.example
app/public/css/styles.css

Refresh balance button styling for screen size between 1024px - 1112px

---

app/frontend/actions.js

Keep transaction form filled after user rejection (from hw wallet)

---

app/frontend/components/common/footer.js
app/frontend/components/pages/receiveAda/addressItem.js
app/frontend/components/pages/txHistory/transactionHistory.js

Replace AdaScan links with Seiza links.

Replace AdaScan with Seiza

---

package.json
server/index.js
server/middlewares/stats.js
server/statsPage.js
yarn.lock

Track overall transactions volume

---

.circleci/config.yml
.eslintrc
app/package.json
app/yarn.lock
package.json
yarn.lock

closes #491 
closes #489
closes #492

Bump dependencies

---

app/frontend/components/pages/exportWallet/exportWalletPage.js
app/frontend/components/router.js
app/public/css/styles.css
server/index.js

I 412 add back button to export keyfile screen

---

server/index.js

closes #516. Adds "maximum-scale" and "user-scalable" properties to "viewport" meta to solve automatic zooming.

Add maximum scale to viewport meta

---

app/frontend/components/app.js
app/frontend/components/common/welcome.js
app/frontend/components/pages/login/loginPage.js
app/frontend/components/pages/login/loginPageSidebar.js
app/frontend/components/pages/sendAda/sendAdaPage.js
app/frontend/components/pages/txHistory/txHistoryPage.js
app/frontend/components/router.js

- this will be required by typescript
- also agrees with official preact doc https://preactjs.com/guide/v8/api-reference/#preacth--preactcreateelement

Fixing preact's `h` calls to always include props.

---

app/frontend/wallet/cardano-wallet.ts
app/tests/src/cardano-wallet.js

- The code is obsolete since d11bc12d5fa8fa28c432d3aa183d4ee06f7b6dbe

Remove obsolete `getNewUtxosFromTxAux` function & associated test

---

app/frontend/components/common/addressDetailDialog.tsx
app/frontend/components/common/footer.tsx
app/frontend/helpers/connect.ts
app/frontend/libs/preact-hooks-unistore.js
app/frontend/walletApp.js

Introduces `useSelector()` and `useActions()` hooks.
This enables ultimate type resolution and works wonders.

Unistore hooks

---

app/frontend/helpers/connect.ts

- I did not properly test the lib version and it does not bind actions correctly

Fix useActions hook

---

app/frontend/wallet/cardano-trezor-crypto-provider.ts

It was introduced in cf2a2e55373e406098cede122eb6358bc9dfc998

Fix regression with Trezor signing

---

app/frontend/actions.ts
app/frontend/translations.ts
app/frontend/wallet/blockchain-explorer.ts
app/frontend/wallet/constants.ts
app/frontend/wallet/shelley/build-transaction.ts
app/frontend/wallet/shelley/helpers/chainlib-wrapper.ts
app/frontend/wallet/shelley/shelley-js-crypto-provider.ts

Functionality fixes and refactors

Submit tx and delegate stake

---

server/index.js

Dont track txsubmissions until we can parse txs.

Comment out tracking tx submissions

---

server/index.js
server/middlewares/statsGoogleAnalytics.js

Tracks transaction count - does not know how to parse values yet.

Hotfix transaction count tracking

---

app/package.json
app/yarn.lock
yarn.lock

upped trezor-connect version to latest

---

app/public/css/styles.css

I 607 fix error modal content overflow

---

app/frontend/actions.js
app/frontend/translations.js
app/frontend/wallet/cardano-wallet.js
app/frontend/wallet/helpers/request.js

Partly addresses #608, just fixing the error message so its more general and includes a case when Adalite backend is down.

I 608 fix misleading error message when backend is down

---

app/frontend/components/pages/receiveAda/addressItem.js
app/frontend/components/pages/txHistory/transactionHistory.js

Switches AdaScan for cardanoExplorer since both Seiza and Adascan have syncing issues

Switch AdaScan for CardanoExplorer

---

app/frontend/actions.ts
app/frontend/components/common/footer.tsx
app/frontend/helpers/getDonationAddress.ts
app/frontend/wallet/byron-tx-planner.ts
app/frontend/wallet/cardano-wallet.ts
app/frontend/wallet/constants.ts
app/frontend/wallet/max-amount-calculator.ts
app/frontend/wallet/shelley/build-transaction.ts

1.) fix login: was failing on trying to call getValidStakepools which is not defined for Byron.
as far as I'm able to tell, returning nothing (but not failing) should be OK
2.) fix entering transaction: was failing on unsupported address format for donation address

Byron - fix login & entering tx amount

---

app/frontend/actions.ts
app/frontend/components/pages/login/loginPage.tsx

* Tx submission: the only problem was reloading stakepool info, which shouldn't be done for Byron
* HW wallet: only added the option to login screen, no additional changes were needed to log in successfully using trezor emulator
(trezor however complained that we're using outdated version, I'll look into that next)

Fix tx submission & add hw wallet login

---

app/tests/src/actions/actions.js
app/tests/src/actions/transaction-actions.js
app/tests/src/actions/wallet-actions.js

Add first testcase for tx action.

Test for transaction actions

---

.env.example
app/frontend/actions.ts
app/frontend/components/pages/delegations/currentDelegationPage.tsx
app/frontend/components/pages/delegations/delegatePage.tsx
app/frontend/components/pages/delegations/shelleyBalances.tsx
app/frontend/components/pages/login/hardwareAuth.tsx
app/frontend/components/pages/login/loginPage.tsx
app/frontend/components/pages/sendAda/confirmTransactionDialog.tsx
app/frontend/helpers/validators.ts
app/frontend/wallet/byron/byron-tx-planner.ts
app/frontend/wallet/cardano-wallet.ts
app/frontend/wallet/constants.ts
app/frontend/wallet/shelley-wallet.ts
app/frontend/wallet/shelley/helpers/addresses.ts
app/frontend/wallet/shelley/shelley-address-provider.ts
app/frontend/wallet/shelley/shelley-crypto-provider-factory.ts
app/frontend/wallet/shelley/shelley-js-crypto-provider.ts
app/frontend/wallet/shelley/shelley-ledger-crypto-provider.ts
app/frontend/wallet/shelley/shelley-transaction-planner.ts
app/frontend/wallet/shelley/shelley-transaction.ts
app/package.json
app/public/css/styles.css
app/tests/src/actions/transaction-actions.js
app/tests/src/cardano-wallet.js
app/yarn.lock
server/helpers/loadConfig.js
server/index.js
server/poolInfoGetter.js

Gets pool info through the server thus bypasses CORS.

get pool info through server

---

app/frontend/actions.ts
app/frontend/wallet/byron/byron-tx-planner.ts
app/frontend/wallet/cardano-wallet.ts
app/frontend/wallet/shelley-wallet.ts
app/frontend/wallet/shelley/shelley-transaction-planner.ts

WIP, 
- moves byron-tx-planning to byron folder, 
- creates tx planning for Shelley, basically, just copy-paste from Byron with the addition of certificates, but not functional nor finished yet, since waiting for the implementation of tx building.

WIP - Shelley transaction planning

---

app/frontend/components/pages/receiveAda/addressItem.tsx
app/frontend/components/pages/txHistory/transactionHistory.tsx

While Seiza is down we are replacing it with Blockchair

Switch Seiza for Blockchair while it's down

---

app/frontend/actions.ts
app/frontend/helpers/NamedError.ts
app/frontend/wallet/address-manager.ts
app/frontend/wallet/byron/cardano-ledger-crypto-provider.ts
app/frontend/wallet/byron/cardano-trezor-crypto-provider.ts
app/frontend/wallet/byron/crypto-provider-factory.ts
app/frontend/wallet/cardano-wallet.ts
app/frontend/wallet/helpers/bip32.ts
app/frontend/wallet/helpers/request.ts
app/frontend/wallet/shelley-wallet.ts
app/frontend/wallet/shelley/shelley-crypto-provider-factory.ts
app/frontend/wallet/shelley/shelley-ledger-crypto-provider.ts
app/frontend/wallet/shelley/shelley-trezor-crypto-provider.ts

Refactor, make arbitrary parameters independent on their order, remove showHelp parameter as it is not used anywhere

Allow NamedError to keep parent stack

---

app/frontend/components/pages/common.tsx
app/frontend/components/pages/delegations/currentDelegationPage.tsx
app/frontend/components/pages/delegations/stakingHistoryPage.tsx
app/frontend/helpers/getEpochEndDateTime.ts
app/frontend/state.ts
app/frontend/wallet/blockchain-explorer.ts
app/frontend/wallet/constants.ts
app/frontend/wallet/shelley-wallet.ts
app/public/css/styles.css
app/tests/src/common/mock.js

New:
- Added new line to the current delegation to show when next reward from currently delegated pool will be distributed
- Added section to current delegation, to show reward from previously delegated pool (only shown when this reward info is different to the reward above)

Show rewards

---

app/frontend/components/pages/sendAda/confirmTransactionDialog.tsx

Add description to deposit in delegation review

---

app/frontend/actions.ts
app/frontend/components/pages/login/hardwareAuth.tsx
app/frontend/translations.ts
app/frontend/wallet/shelley/shelley-ledger-crypto-provider.ts
app/package.json
app/yarn.lock
package.json

Changes:
* Force WebUSB transport with Ledger when selected #778

Release 5.1.20

---

app/frontend/actions.ts
app/frontend/components/pages/accounts/accountsDashboard.tsx
app/frontend/state.ts
app/frontend/wallet/account-manager.ts
app/frontend/wallet/shelley-wallet.ts
app/tests/src/common/account-manager-settings.js
app/tests/src/wallet/account-manager.js
package.json

* Fix account discovery if max account is used, set max account to 20 for Trezor (aaaac8b)

Release 6.0.2

---

app/frontend/components/pages/staking/stakingPage.tsx

Update staking page pools

---

app/frontend/wallet/shelley/shelley-ledger-crypto-provider.ts
app/package.json
app/yarn.lock

Changes: 
- Updates ledger lib and ledger transport libraries
- Capture message to sentry if the transport creation fails, for debugging purposes.

Update ledger lib

---

app/frontend/wallet/account.ts
app/frontend/wallet/byron/byron-address-provider.ts
app/frontend/wallet/constants.ts
app/frontend/wallet/shelley/helpers/addresses.ts
app/frontend/wallet/types.ts
app/tests/src/shelley.js
server/helpers/loadConfig.js

Changes: 
- Refactors address encoding so it works with testnet addresses and happens in one place. 
- Adds new network for mary
Todo:
- Fix all parameters in the network constant.
- Fix failing tests

Support testnet

---

app/frontend/wallet/account.ts
app/frontend/wallet/blockchain-explorer.ts
app/frontend/wallet/byron/byron-address-provider.ts
app/frontend/wallet/constants.ts
app/frontend/wallet/explorer-types.ts
app/frontend/wallet/shelley/helpers/addresses.ts
app/frontend/wallet/types.ts
app/tests/src/shelley.js
package.json
server/helpers/loadConfig.js

Changes:
* added support for testnet
* bugfix for the app crashing for wallets that happen to delegate to stake pools that are not among those "valid"

Release 6.0.14

---

app/frontend/components/common/infoModal.tsx
app/frontend/localStorage.ts

This code is already in the production deployment via manual deploy. This PR adds it to develop as well so that it's not lost

Add survey news

---

app/frontend/actions.ts
app/frontend/components/pages/delegations/currentDelegationPage.tsx
app/frontend/components/pages/delegations/delegateInput.tsx
app/frontend/components/pages/delegations/delegatePage.tsx
app/frontend/translations.ts
app/frontend/wallet/blockchain-explorer.ts

Changes
- Fix error not showing on when pool was null
- Refactor delegation input validation to separate function
- Add new error for case when search by ticker is unavailable
- Hide null fields in UI in current delegation page

Fix delegation input errors

---

app/frontend/components/common/searchableSelect.tsx
app/frontend/components/pages/delegations/common.tsx
app/frontend/components/pages/sendAda/sendAdaPage.tsx
app/frontend/components/pages/txHistory/transactionHistory.tsx
app/frontend/helpers/onSubTreeBlur.ts
app/public/css/styles.css

This also fixes bug when user clicks on dropdown button and it reopens instead of toggle.

Add cardano scan links to multi-asset tokens

---

app/frontend/actions.ts
app/frontend/components/pages/dashboard/dashboardPage.tsx
app/frontend/components/pages/delegations/delegatePage.tsx
app/frontend/components/pages/delegations/deregisterStakeKey.tsx

* introduce future refactor comments

Fix race-condition for stake-key deregister

---

app/frontend/translations.ts

Related to https://github.com/vacuumlabs/adalite/issues/882

Update translation for U2F DEVICE_INELIGIBLE

---

app/frontend/actions.ts
app/frontend/actions/error.ts
app/frontend/components/pages/accounts/delegationModal.tsx
app/frontend/components/pages/accounts/sendTransactionModal.tsx
app/frontend/components/pages/delegations/delegateInput.tsx
app/frontend/components/pages/delegations/delegatePage.tsx
app/frontend/components/pages/delegations/stakePoolInfo.tsx
app/frontend/components/pages/sendAda/sendAdaPage.tsx
app/frontend/state.ts
app/frontend/types.ts

* Based on the initial 2 commits this was expected to be easy refactor but:
* After the second commit, I got myself into the issue shown on the image below (after submit delegation). I only exchanged "connect" for "useActions", but when I started to investigate why the error happens, I just felt that this part strongly needs refactor, as it was very difficult for me to figure out the flow of information
**Incompatibility changes**
* if the pool hash is invalid, the fee is not calculated, but I consider this to be expected.
=> divide actions part 1 PR should be merged first

Send and delegate connect refactor

---

app/frontend/components/common/asset.tsx
app/frontend/components/pages/sendAda/confirmTransactionDialog.tsx
app/frontend/components/pages/sendAda/multiAssetsPage.tsx
app/frontend/components/pages/sendAda/sendAdaPage.tsx
app/frontend/components/pages/stringEllipsis.tsx
app/frontend/components/pages/txHistory/transactionHistory.tsx
app/frontend/wallet/shelley/helpers/addresses.ts
app/public/css/styles.css
app/tests/src/tokenBundle.js

Adds asset fingerprint
As we discussed, for some time we want to show also the policy id, we ll remove it when trezor releases.

Asset fingerprint

---

app/frontend/actions/address.ts
app/frontend/actions/poolOwner.ts
app/frontend/actions/transaction.ts
app/frontend/actions/wallet.ts
app/frontend/components/pages/advanced/poolOwner.tsx
app/frontend/components/pages/delegations/shelleyBalances.tsx
app/frontend/selectors.ts
app/frontend/state.ts
app/frontend/types.ts
app/frontend/wallet/shelley-wallet.ts
app/frontend/wallet/shelley/shelley-js-crypto-provider.ts
app/frontend/wallet/shelley/shelley-ledger-crypto-provider.ts
app/frontend/wallet/shelley/shelley-trezor-crypto-provider.ts
app/frontend/wallet/types.ts
app/tests/src/actions/wallet-actions.js

- Refactor wallet names to an enum
- Refactor usingHwWallet state var into a selector
- Remove useless keys from State (isDelegationValid, currentDelegation)

Refactor state 3

---

app/frontend/actions/wallet.ts
app/frontend/components/pages/login/demoWalletWarningDialog.tsx
app/frontend/components/pages/login/generateMnemonicDialog.tsx
app/frontend/components/pages/login/hardwareAuth.tsx
app/frontend/components/pages/login/keyFileAuth.tsx
app/frontend/components/pages/login/logoutNotification.tsx
app/frontend/components/pages/login/nonShelleyCompatibleDialog.tsx
app/frontend/components/pages/receiveAda/receiveRedirect.tsx
app/frontend/components/pages/sendAda/rawTransactionModal.tsx
app/frontend/components/pages/txHistory/transactionHistory.tsx

This PR converts connect - function/class components to function components with useSelector + useActions. The main focus is on components which are not that likely to be touched by anyone during other refactors.

Connect to hooks 1

---

app/frontend/actions/general.ts
app/frontend/actions/wallet.ts
app/frontend/components/common/alert.tsx
app/frontend/components/pages/dashboard/dashboardPage.tsx
app/frontend/components/pages/login/wantedAddressesModal.tsx
app/frontend/state.ts
app/frontend/wallet/constants.ts
app/public/css/styles.css

Resurrection of https://github.com/vacuumlabs/adalite/commit/a31a597abfac4b67401c33aef19f92a8eada3406. Previously, we thought the problem was solved, so I removed it, but we need it again.
Here's how it looks:

Bring back big delegator private message

---

README.md
app/frontend/components/common/loadingOverlay.tsx
app/frontend/components/pages/accounts/accountDropdown.tsx
app/frontend/components/pages/accounts/accountTile.tsx
app/frontend/components/pages/accounts/accountsDashboard.tsx
app/frontend/components/pages/dashboard/dashboardPage.tsx

* removed from:
loading
accountDashboard
dashboardPage
accountDropdown
accountTile
* improves: TS inference & hot-reloading experience

Remove connect from chosen components

---

app/frontend/actions/delegate.ts
app/frontend/actions/poolOwner.ts
app/frontend/components/pages/delegations/delegatePage.tsx
app/frontend/components/pages/delegations/shelleyBalances.tsx
app/frontend/components/pages/sendAda/confirmTransactionDialog.tsx
app/tests/src/actions/transaction-actions.js

* Remove actions with "Old" postfix from delegation flow
* Remove race-condition check which is no longer necessary
* Move "deregisterStakeKey" to "delegate" file, instead of "poolOwner" file
For easier understanding, I suggest to review commit by commit.

Delegate transaction refactor

---

app/frontend/wallet/shelley-wallet.ts

Remove 20 accounts limit for trezor

---

app/frontend/errors/errorMessages.ts
app/frontend/errors/internalErrorReason.ts
app/frontend/helpers/validators.ts

Fix address validation

---

app/frontend/wallet/shelley/shelley-trezor-crypto-provider.ts

Fix trezor staking key deregistration

---

app/frontend/helpers/validators.ts
app/tests/src/helpers/parseCoins.js
app/tests/src/index.js

Fix parsing of ADA amount

---

app/frontend/errors/errorMessages.ts
app/frontend/errors/errorsWithHelp.ts
app/frontend/wallet/shelley/shelley-ledger-crypto-provider.ts

Motivation: I was testing webhid on Chrome further and I realized that when the user hits "cancel" in the webhid pop-up, the window closes and Adalite seems to end up being stuck in an infinite "loading wallet data" state with the spinner. This seems to be caused by non-working U2F in Chrome 91 which Adalite automatically falls back to after getting a cancellation error from WebHID transport and can be quite confusing if users on Chrome actually face issues with WebHID
I'm not actually sure at this point, why we introduced the U2F fallback as Myether wallet doesn't seem to do it: https://github.com/MyEtherWallet/MyEtherWallet/blob/bd8416a199da87a29f24bc4b5668a0273f34488a/src/wallets/hardware/ledger/index.js#L148
Looking at the commit where we introduced it I'm none the wiser as it doesn't …

Remove Ledger transport fallback to U2F, fix wallet logout

---

app/package.json
app/yarn.lock

related to https://github.com/LedgerHQ/ledgerjs/issues/607

Update ledgerjs webusb transport to version 5.53.0

---

app/package.json
app/yarn.lock

related to: https://github.com/LedgerHQ/ledgerjs/issues/607#issuecomment-854117544

Update webusb transport

---

app/frontend/components/common/infoModal.tsx
app/frontend/localStorage.ts

Add hiring news

---

app/frontend/wallet/account.ts
app/frontend/wallet/helpers/shuffleArray.ts
app/tests/src/index.js
app/tests/src/wallet/account/account.js
app/tests/src/wallet/account/utxo-settings.js

Motivation : #1077 
Changes: 
- if a user is sending tokens, utxos that contain this token are selected first, then onlyAda utxos, and then the rest of the token utxos.
Gotcha: 
- I need to do some manual testing but checkout the tests

Optimize utxo selection

---

app/frontend/components/common/infoModal.tsx

Plan is to merge this on Monday, if no problems with token registry occur.

Update news with token registry re-release

---

app/frontend/helpers/removeNullFiels.ts
app/frontend/wallet/shelley/shelley-trezor-crypto-provider.ts
app/frontend/wallet/shelley/trezor-types.ts
app/package.json
app/yarn.lock

This reverts commit 68becc7b7898f2b4be9ab1a6306092520191dc70.
This reverts commit caf7ae8c9c4a12997338397aff7bb885a301fe06.

Revert Trezor FW changes

---

app/frontend/components/common/infoModal.tsx
app/frontend/components/pages/delegations/stakingHistoryPage.tsx
app/frontend/components/pages/txHistory/transactionHistory.tsx
app/frontend/helpers/common.ts
app/frontend/localStorage.ts
app/frontend/wallet/backend-types.ts
app/frontend/wallet/blockchain-explorer.ts
app/public/css/styles.css

Reward warning, filtering of failed txs, news

---

app/package.json
app/yarn.lock
package.json
yarn.lock

Run yarn-audit-fix and add resolutions

---

app/frontend/components/common/contactForm.tsx
app/frontend/components/pages/dashboard/premiumBanner.tsx
app/frontend/components/pages/login/wantedAddressesModal.tsx
app/frontend/wallet/constants.ts

AFTER MERGE TODO: UPDATE ENV ADALITE_SUPPORT_EMAIL!

Update support emails throughout the site

---

app/frontend/components/common/infoModal.tsx
app/frontend/localStorage.ts

Add NuFi beta tester news

---

app/frontend/components/pages/voting/votingCard.tsx
app/frontend/helpers/common.ts

Reword catalyst closed status explanation

---

app/public/css/0-1366px.css
app/public/css/styles.css

Follow-up PR to #1207 , fixes absence of the "close" button at the bottom of the modal on the news page

Apply sticky footer css without media query

---

app/package.json
app/yarn.lock

Fixes issues with Catalyst registration introduced in previous trezor-connect release

Update trezor-connect version

---

app/frontend/components/pages/nufiPreview/nufiPreviewPage.tsx
app/public/css/0-1024px.css
app/public/css/0-767px.css
app/public/css/styles.css
server/index.js

improve mobile view on the `/nufi` screen

Improve nufi preview responsivness

---

app/bitbox02-api.d.ts
app/frontend/components/pages/common.tsx
app/frontend/components/pages/receiveAda/myAddresses.tsx
app/frontend/components/pages/sendAda/sendAdaPage.tsx
app/frontend/errors/errorMessages.ts
app/frontend/wallet/constants.ts
app/frontend/wallet/shelley/shelley-bitbox02-crypto-provider.ts
app/package.json
app/yarn.lock

The BitBox02 supports tokens since firmware v9.9.0.

bitbox02: enable token support

---

app/frontend/components/pages/login/loginPageSidebar.tsx
app/public/css/styles.css

Update NuFi message

---

.circleci/config.yml
.iyarc
app/.iyarc
app/frontend/components/pages/login/loginPageSidebar.tsx
app/frontend/wallet/blockchain-explorer.ts
app/package.json
app/public/css/styles.css
app/yarn.lock
package.json
yarn.lock

Main changes:
* (hotfix) increase ttl of requests cache to 15 seconds to reduce repeated requests in most cases as response times from our backend have increased lastly, causing the cache to be stale prematurely
* upgrade wording of NuFi announcement

Release 6.9.20

---

app/frontend/actions/reloadWallet.ts
app/frontend/helpers/cacheResults.ts
app/frontend/tokenRegistry/tokenRegistry.ts
app/frontend/wallet/blockchain-explorer.ts
app/frontend/wallet/shelley-wallet.ts

https://vacuum.atlassian.net/browse/ADLT-1033

Invalidate the request cache after a transaction is submitted

---

app/frontend/actions/accounts.ts
app/frontend/actions/common.ts
app/frontend/actions/delegate.ts
app/frontend/actions/send.ts
app/frontend/actions/transaction.ts
app/frontend/actions/voting.tsx
app/frontend/types.ts
app/frontend/wallet/account.ts
app/tests/src/actions/transaction-actions.js
app/tests/src/wallet/account/account.js

https://vacuum.atlassian.net/browse/ADLT-1040
How to test: write a value into the send element and observe F12/network.

[ADLT-1040] Computation of fees results in address-rediscovery

---

app/frontend/components/common/asset.module.scss
app/frontend/components/common/asset.tsx
app/frontend/components/pages/advanced/signPoolCertTxModal.tsx
app/frontend/components/pages/sendAda/confirmTransactionDialog.tsx
app/frontend/components/pages/sendAda/multiAssetsPage.module.scss
app/frontend/components/pages/sendAda/multiAssetsPage.tsx
app/frontend/components/pages/sendAda/sendAdaPage.tsx
app/frontend/components/pages/txHistory/transactionHistory.tsx
app/public/css/styles.css
package.json

Display a fingerprint as a fallback value in the case of a human nonreadable asset name

Release 6.9.24

---

app/frontend/components/common/welcome.tsx
app/frontend/components/pages/login/hardwareAuth.tsx
app/frontend/components/pages/login/loginPage.tsx
app/frontend/components/pages/login/loginPageSidebar.tsx
server/index.js

https://vacuum.atlassian.net/browse/ADLT-1300

Update description to include Ledger Nano S Plus

---

.circleci/config.yml
.iyarc
app/cypress/integration/sendingTab.spec.ts
app/frontend/components/common/infoModal.tsx
app/frontend/localStorage.ts
app/package.json
app/yarn.lock
package.json
yarn.lock

* added announcement regarding NuFi extension
* updated moment and release-it libraries to address vulnerability reports
* fixed integration test which was failing because the cypress testing mnemonic received additional tokens and the test wasn't designed to handle that

Release 6.9.27

---

app/frontend/components/common/infoModal.tsx
app/frontend/localStorage.ts

Add "vote in project catalyst" announcement in news.

Add vote in project catalyst announcement

---

app/frontend/wallet/account.ts
package.json

Release 6.10.1

---

app/frontend/wallet/helpers/cbor.ts
app/frontend/wallet/shelley/helpers/stakepoolRegistrationUtils.ts
app/frontend/wallet/shelley/transaction/computeTxPlan.ts
app/frontend/wallet/shelley/transaction/constants.ts
app/frontend/wallet/shelley/transaction/index.ts
app/frontend/wallet/shelley/transaction/shelley-transaction-planner.ts
app/frontend/wallet/shelley/transaction/utils.ts
app/tests/src/common/tx-settings.ts
app/tests/src/computeChange.ts
app/tests/src/tokenBundle.ts

Jira issue: [ADLT-1697](https://vacuum.atlassian.net/browse/ADLT-1697)
**Motivation**
Update min ADA calculation formula to match latest changes introduced in Babbage era.
**Previous behavior**
Based on:
- https://github.com/input-output-hk/cardano-ledger/blob/8817304c300dd60099054dd66d9a1ecbd33bfb3a/doc/explanations/min-utxo-mary.rst
**New behavior**
Based on:
- https://cips.cardano.org/cips/cip55/#thenewminimumlovelacecalculation
- https://hydra.iohk.io/build/15339994/download/1/babbage-changes.pdf page 9
**Changes**
Update function that implements mentioned formula.
**How to test**
Try making a transaction with tokens and without tokens, try using max button, try making transaction with 1 ADA.
**Checklist**
[ADLT-594]: https://vacuum.atlassian.net/browse/ADLT-594?atlOrigin=eyJpIjoiNWRkN …

Update min ADA calculation formula

---

.iyarc
app/.iyarc
app/frontend/components/common/infoModal.tsx
app/frontend/components/pages/login/loginPage.tsx
app/frontend/localStorage.ts
app/public/css/styles.css

Promote catalyst from login page

---

app/frontend/components/common/infoModal.tsx

#Motivation
- remind user that of the catalyst proposal deadline

Add catalyst reminder to news [ADLT-2205]

---

app/frontend/components/pages/login/loginPage.tsx
app/public/css/styles.css

reverting https://github.com/vacuumlabs/adalite/pull/1384/commits/1211bc2fc8a211c3bcc7174bd35d22e4ab08b8f3

Revert catalyst promotio banner

---

app/frontend/components/pages/login/loginPage.tsx
app/public/css/styles.css

This reverts commit ea14820304b894e43f6df22a5b151e8f1b0423cc.

Revert banner for catalyst proposal

---

app/frontend/components/common/welcome.tsx
app/frontend/components/pages/login/hardwareAuth.tsx
app/frontend/components/pages/login/loginPage.tsx
app/frontend/components/pages/login/loginPageSidebar.tsx
app/frontend/wallet/shelley/shelley-ledger-crypto-provider.ts
app/frontend/wallet/shelley/shelley-trezor-crypto-provider.ts
app/package.json
app/yarn.lock
package.json

Update trezor/ledger libs to latest and add mention of Trezor Safe 3 support

Release 6.12.0

---

app/frontend/components/pages/delegations/stakingHistoryPage.tsx
app/frontend/components/pages/sendAda/multiAssetsPage.module.scss
app/frontend/components/pages/sendAda/multiAssetsPage.tsx
app/frontend/components/pages/txHistory/transactionHistory.tsx
app/frontend/wallet/blockchain-explorer.ts
app/frontend/wallet/shelley/helpers/addresses.ts
app/public/css/styles.css
package.json

performance fixes consisting in limiting shown tx history/tokens

Release 6.13.0

---

app/frontend/components/pages/login/ledgerTransportSelect.tsx
app/frontend/errors/errorMessages.ts
app/frontend/types.ts
app/frontend/wallet/shelley/helpers/transports.ts
app/frontend/wallet/shelley/shelley-ledger-crypto-provider.ts
app/package.json
app/yarn.lock

Reason: UX in Firefox was misleading, giving false hopes that Ledger may somehow work there

fix: drop ledger u2f transport which (AFAIK) no longer works anywhere

---

app/frontend/components/common/nufiBanner.tsx

Motivation: ensure consistency of banner across re-renders, preventing any potential flickering should the component re-render

refactor: polish banner logic using react hooks
