vacuumlabs/adalite

- frontend/actions.js
- frontend/components.js
- frontend/translations.js
- frontend/walletApp.js
- wallet/cardano-wallet.js
II simplified the validation behavior so that the transaction fee does not disapper when computing it but it turns red and stays like that until the transaction fee computation passes.
I tried also to avoid the disappearing of the validation message when the address changes but I could not find a solution that I would be satisfied with. Feel free to suggest any.
> Simplify transaction validation behavior

- frontend/components.js
- public_wallet_app/css/styles.css
- does not collapse on click on status part
- does not solve the problem of rendering page wider than narrow screens at receive (transparent tooltips widen the page over screen edge)  
closes #71
> Collapse mobile menu on click on nav elements

- frontend/components.js
- public_wallet_app/css/styles.css
Transaction history table was overflowing and forced whole page to scroll... Same thing for addresses in "receive" tab
> Fix overflows on mobile

- public_wallet_app/css/styles.css
The demo button has blinking on right side of button when it was hovered. It is caused with transition and transform scale
> Remove transition from demo button to remove glitch

- frontend/components.js
- package.json
- public_wallet_app/css/styles.css
- test/tests/cardano-mnemonic-crypto-provider.js
- test/tests/mnemonic.js
- wallet/cardano-mnemonic-crypto-provider.js
- wallet/hd-node.js
- wallet/helpers/derivePublic.js
- wallet/helpers/pbkdf2.js
- wallet/mnemonic.js
- yarn.lock
Now you can insert into the input the 27 word paper wallet mnemonic and the wallet will get properly loaded. The proper way of working is shown in the tests (the "mnemonic.js" one). You can try loading the paper wallet string from the tests and see that the wallet was loaded by checking for the presence of the address "DdzFFzCqrhssvx7eAtDT2xbQtVeRVjCktAEg4sc3gmSFE6RFBadLVZX2e8ByfawtASMBeUtNMsyauaSSG2TP3Rgv3V94xLzmt67fJG4z" between the receive addresses. You can also generate the paper wallet yourself in Daedalus and verify that the first receive address to appear in cardanolite matches the one from the PDF generated by Daedalus.
> Paper wallet support

- frontend/components/pages/dashboard/transactionHistory.js
There is trade-off for having locale enabled date strings - they are not "prettyfied" by padding with zeros
> Change transaction date to local

- app/frontend/components/pages/login/generateMnemonicDialog.js
- app/frontend/components/pages/login/mnemonicAuth.js
closes #144 fix: enable selecting text in generateNewMnemonic dialog
closes #145 fix: wrong mnemonic prevent new one or demo -> err moves layout
> fix: wrong mnemonic prevent new one or demo 

- app/frontend/actions.js
- app/frontend/components/common/svg.js
- app/frontend/components/pages/login/loginPage.js
- app/frontend/components/pages/login/mnemonicAuth.js
- app/frontend/components/pages/send_ada/sendAdaPage.js
- app/frontend/helpers/NamedError.js
- app/frontend/helpers/sleep.js
- app/frontend/translations.js
- app/frontend/wallet/address.js
- app/frontend/wallet/blockchain-explorer.js
- app/frontend/wallet/cardano-wallet.js
- app/frontend/wallet/helpers/request.js
- server/transactionSubmitter.js
The spinner now should be displayed until the transaction actually appears in the blockchain explorer, so the user won't be confused.
If the transaction fails to appear within ~100 seconds (20 retries * 5s sleep), an error should be displayed where the user is notified about the transaction id, so he can check it later.
I also refactored and fixed error handling when submitting transactions. I added NamedError helper. Most of the errors were not displayed/handled propery, since they did not make it to the "sendResponse" state variable.
I also refactored translations so they have a nicer API and fail gracefully if translation code is not present
> show spinner until transaction appears in explorer

- package.json
- server/index.js
- server/middlewares/stats.js
- server/mocking.js
- server/statsPage.js
- server/transactionSubmitter.js
- yarn.lock
Added counter of transaction submissions whether they are successful or not. The results should appear in the stats page as soon as you attempt to submit a transaction, if you have set the REDIS_URL properly in .env
I initially tried to filter out unsuccessful tx submission attempts, but I did not find a nice way to intercept the content of the response, maybe you can suggest something.
> added transactions counter to stats

- app/frontend/actions.js
- app/frontend/components/pages/sendAda/sendAdaPage.js
closes #200 and fixes other weird behaviour
`validateSendForm` now always validates both fields and presentation of resulting validation is handled in component.
(Includes removing `isSendAddressValid` from state as it is ~duplicate of `validationError` / can be derived)
Suspending the address error display until inputting amount is clashing with behavior of 'MAX' button. Unified to match the button as it is more intuitive. Besides, not stressing user while typing email makes sense but the address will most likely be copy-pasted in in >99% of cases.
`sendMaxFunds` changes fix other errors overriding 'SendAmountCantSendMaxFunds', which imo should be the more important one
Displaying transaction fee when address isn't valid can cause (see picture) so I added checks for valid address
> Send form validation fixes

- app/frontend/components/common/footer.js
- app/public/css/styles.css
+ smaller footer padding, `1.5rem` was too much IMO, changed it to `1rem`
> align text in footer before VacuumLabs logo to be on the same line

- app/frontend/wallet/helpers/alertIfUnsupportedTrezorFwVersion.js
closes #217 
the problem of the previous check was that it failed to recognize version 2.0.10 (not released yet) as higher since there was a simple alphabetical comparison of version strings so I replaced it with a more robust one.
> Fix trezor version check

- app/frontend/components/pages/txHistory/transactionHistory.js
- app/frontend/helpers/formatDate.js
Closes https://github.com/vacuumlabs/adalite/issues/203
> format date in TransactionHistory to have same length

- app/frontend/actions.js
- app/frontend/components/pages/login/keyFileAuth.js
- app/webpack.build.config.js
I was tinkering with code splitting and I fixed webpack along the way to produce a nicer output and it builds in prod mode on production. I disabled uglification so the code is more readable when somebody wants to examine it and added source map to improve debugging. This should also be helpful to fully implementing CSP #236 , since evals from webpack build were removed and the only eval remaining being in init.js which I hope could be overcome somehow.
> Remove code splitting, fix webpack build, add source map

- app/public/js/init.js
- server/index.js
- server/middlewares/csp.js
closes #183 
Added Content-Security-Policy header with middleware
the directives could be made more secure by:
- restricting `connect-src` to only sources we use (impact on maintainability)
- refactoring app in pursuit of removing `unsafe-eval` and maybe scripts `unsafe-inline` (eval seems more complex then just refactoring `init.js`, the inline scripts might be possible, inline css probably isn't)
> Added content security policy middleware

- app/frontend/actions.js
- app/frontend/components/common/addressDetailDialog.js
- app/frontend/components/pages/sendAda/rawTransactionModal.js
- app/frontend/components/pages/sendAda/sendAdaPage.js
- app/frontend/store.js
- app/frontend/wallet/cardano-wallet.js
- app/public/css/styles.css
- app/tests/src/cardano-wallet.js
Closes https://github.com/vacuumlabs/adalite/issues/254.
I couldn't get it to work with the demo wallet, possibly because there weren't enough funds, but at least I refactored the functions to take addresses first and set up the CSS.
> show raw unsigned transaction in modal

- app/frontend/components/common/modal.js
- app/frontend/components/pages/login/welcome.js
- app/public/css/styles.css
Closes #332 
Removed `closeHandler` and added check for `title` to `Modal`. `closeHandler` is not needed as we don't want the modal to be closeable and the check for the `title` prevents rendering an empty `.modal-head` element.
> Mobile Welcome To Adalite modal

- app/frontend/components/pages/txHistory/transactionHistory.js
- app/public/css/styles.css
Closes #348
Refactored `.transaction-address` - removed the outer `div` as it was not needed.
> Mobile Transactions

- app/frontend/actions.js
- app/frontend/components/common/loadingOverlay.js
- app/frontend/components/pages/sendAda/confirmTransactionDialog.js
- app/frontend/components/pages/sendAda/donateThanksModal.js
- app/frontend/components/pages/sendAda/sendAdaPage.js
- app/frontend/components/pages/sendAda/transactionErrorModal.js
- app/public/assets/ada_symbol_grey.svg
- app/public/css/styles.css
Closes #342
Styled `SendADA` component, removed unnecessary components & code, added missing modals, changed styling of the `LoadingOverlay`.
Added `showTransactionErrorModal & closeTransactionErrorModal` handlers. Removed `waitingForTrezor` from the submit button as a loading overlay makes more sense.
Should wait for copy by @kuchtee as some modals have incorrect or just `lorem` texts (left a `TODO`).
> Style SendADA & Loader

- .circleci/config.yml
- app/frontend/wallet/blockchain-explorer.js
- app/package.json
- app/tests/src/common/mock.js
- app/yarn.lock
since the new backend is ready, we can revert to our own utxo endpoint, which won't be lagging anymore.
I fixed circleci dependencies caching along the way, and updated borc package, as a "hack" to bump the circleci cache. If I understand right, circleci was caching old node_modules, because it was caching based on package.json instead of yarn.lock and it also attempted to fallback to old cache if no cache entry was present, which also caused old node modules to be present.
> use old utxo endpoint again

- .env.example
- server/transactionSubmitter.js
Redirect transaction submits to the new backend service. Its endpoint
takes the body in base64 format and neither takes nor returns the hash,
therefore the body needs to be reformatted and when checking whether
the transaction was submitted successfully, the hash from signed
transaction is used instead of the hash from response. The old submitter
was not deleted yet, since it can serve as a fallback option. #363
> Redirect submits to the new backend service

- app/public/css/styles.css
The `donations` list was wrapping on smaller devices, removing the `right margin` from the last `donations-item` will give them a bit more space and it's not needed.
> Mobile Footer donations fix

- app/public/css/styles.css
Removed the `transition` from `.button` as discussed personally, all the buttons are now without transitions. Also removed duplicate `var` declarations regarding `transitions`.
> Unify button hovers

- app/frontend/wallet/cardano-trezor-crypto-provider.js
- app/frontend/wallet/cardano-wallet-secret-crypto-provider.js
- app/frontend/wallet/cardano-wallet.js
- app/frontend/wallet/helpers/CachedDeriveXpubFactory.js
The purpose of this refactor is to extract the deriveXpub caching logic to a single place and to make clear the (potential) asynchronicity of the operation. I changed the name of the trezorVerifyAddress function as well, to be more abstract, since we may support more hw wallets in the future.
> refactor deriveXpub to eliminate repetition from crypto providers

- app/frontend/helpers/validators.js
- app/frontend/wallet/mnemonic.js
Fix a bug that caused any mnemonic with 27 words to be considered valid.
Currently, every word of the mnemonic needs to be in the bip39
dictionary, but the paper wallet mnemonic is not decoded. Mnemonic
validator was simplified.
> Fix paper wallet mnemonic validation

- .circleci/config.yml
- Procfile
- yarn.lock
Upgrade dependencies to fix a vulnerability found by yarn audit. Run yarn audit on CircleCI and before deploying a new release. Switch to a newer CircleCI node image which supports yarn audit. Closes #444
> Upgrade dependencies and add automatic audit

- app/frontend/actions.js
- app/frontend/wallet/cardano-ledger-crypto-provider.js
- app/package.json
- app/yarn.lock
U2F support is being discontinued by Ledger due to the problems with Chrome and Windows 10 that recently appeared: https://www.ledger.com/2019/05/17/windows-10-update-sunsetting-u2f-tunnel-transport-for-ledger-devices/ therefore only webusb will be kept as recommended
> Disable u2f transport for ledger due to its sunsetting

- app/frontend/components/pages/receiveAda/addressItem.js
- app/frontend/components/pages/txHistory/transactionHistory.js
- app/public/css/styles.css
Temporarily add AdaScan links for transaction history and addresses on
top of Seiza links.
> Temporarily add AdaScan links

- .env.example
- app/frontend/actions.js
- app/frontend/components/app.js
- app/frontend/components/common/contactForm.js
- app/frontend/components/common/footer.js
- app/frontend/components/common/modal.js
- app/public/css/styles.css
- server/helpers/loadConfig.js
Add a contact form modal which can be opened by a link in the footer.
The modal contains some hints that can make self-diagnosis easier.
The user can also send a message to the support email via Formspree.
The support email address is stored in .env. Closes #473
> Add contact form modal

- server/middlewares/statsGoogleAnalytics.js
Since GA can't track float numbers (only ints), we floor them and send them as integers
> Floor send and change amounts for GA

- app/frontend/actions.js
- app/frontend/wallet/cardano-wallet.js
- app/tests/src/cardano-wallet.js
Should solve #500. Created two seeds instead of one to eliminate correlation between tx inputs generator and change address generator. These seeds are re-generated after each transaction submit.
> Generate new seeds after transaction submit

- app/frontend/components/common/navbar/navbarAuth.js
Solves #514 
Remembering scroll position is default react behaviour. Therefore we need to reset scroll position when route changes. PR changes inspired by
https://medium.com/@nasir/reset-scroll-position-on-change-of-routes-react-a0bd23093dfe
https://codepen.io/Yuschick/post/react-reset-scroll-position-when-changing-routes
https://github.com/ReactTraining/react-router/issues/4278#issuecomment-267093084
Attached componentDidMount and componentDidUpdate to authNavbar, since every page that this navbar is on, needs special scrolling positions for mobile.
> Scroll to top on route change

- app/frontend/components/common/contactForm.js
closes #526 . Fields are now not reset instantly after submitting the form, instead they are reset after closing the modal.
> Reset form fields after closing window

- app/frontend/components/common/addressDetailDialog.tsx
- app/frontend/components/common/contactForm.tsx
- app/frontend/components/common/errorModal.tsx
- app/frontend/components/common/modal.tsx
- app/frontend/components/common/unexpectedErrorModal.tsx
- app/frontend/components/pages/login/demoWalletWarningDialog.tsx
- app/frontend/components/pages/login/generateMnemonicDialog.tsx
- app/frontend/components/pages/login/loginPage.tsx
- app/frontend/components/pages/login/logoutNotification.tsx
- app/frontend/components/pages/login/stakingBanner.tsx
- app/frontend/components/pages/login/walletLoadingErrorModal.tsx
- app/frontend/components/pages/sendAda/confirmTransactionDialog.tsx
- app/frontend/components/pages/sendAda/donateThanksModal.tsx
- app/frontend/components/pages/sendAda/rawTransactionModal.tsx
- app/frontend/components/pages/sendAda/sendAdaPage.tsx
- app/frontend/components/pages/sendAda/transactionErrorModal.tsx
- This better describes the intent and is in line with React Native's modal
> Refactor - rename Modal's closeHandler to onRequestClose

- app/frontend/actions.ts
- app/frontend/components/common/balance.tsx
- app/frontend/components/pages/txHistory/transactionHistory.tsx
- app/frontend/helpers/adaConverters.ts
- app/frontend/helpers/printAda.ts
- app/frontend/helpers/validators.ts
- app/frontend/state.ts
- app/frontend/translations.ts
- app/frontend/wallet/cardano-wallet.ts
With a small hack called "tagged types", typescript can be convinced to check we have correct Ada/Lovelace units
> Introduce explicit Ada vs Lovelace number distinction

- app/frontend/wallet/address-manager.ts
- app/frontend/wallet/cardano-wallet.ts
- app/tests/src/address-manager.js
I believe this option was relevant only in the past
when the code was complected with blockchain explorer.
> Remove `disableCaching` from AddressGenerator

- app/frontend/actions.js
- app/frontend/helpers/NamedError.js
Previously, if request fetching the conversion rates failed, an error was thrown. This error wasnt present in translations so in case it occured, it was considered unexpected so `unexpectedErrorModal` was shown. This has been shown to be happening too often thus bothering the users.
> Fix errorModal showing on conversionRatesError

- app/frontend/actions.ts
- app/frontend/components/pages/dashboard/dashboardPage.tsx
- app/frontend/components/pages/delegations/currentDelegationPage.tsx
- app/frontend/components/pages/delegations/delegatePage.tsx
- app/frontend/components/pages/sendAda/sendAdaPage.tsx
- app/frontend/components/pages/txHistory/transactionHistory.tsx
- app/frontend/state.ts
- app/frontend/translations.ts
- app/frontend/wallet/blockchain-explorer.ts
- app/frontend/wallet/shelley-wallet.ts
- app/frontend/wallet/shelley/helpers/addresses.ts
- app/public/css/styles.css
- fixes problem with no enough balance to change delegation
- fixes css grid so pool id doesnt break the whole viewport
- make unselected tabs colored grey
- disables revoke and throws error when converting legacy if not enough balance to pay the fee
- remove conversionRates error throwing
- disables addressInfos catching as aj temporary solution to tx history bug
- separetes tx success message on both tabs
- adds single address utxos to possible utxos when changing delegation
> Fix balance error and current delegation grid arrangement

- server/index.js
- server/middlewares/errorHandler.js
Motivation: Our logs are getting polluted with exceptions related to IP denials due to a missing error handler
Solution: Add generic error handler that catches the IpDeniedError and translates it into a 401 response, omitting redundant logging and translates the rest of unhandled errors into an error 500 with "Internal Server Error" message, logging the error to the console for future debugging.
Testing: tested locally, behaves as expected both for IpDeniedError and for unhandled errors
> Add server error handler

- server/transactionSubmitter.js
Motivation: over the last few weeks we are seeing like a 10% fail rate of transaction submissions. As of now, we don't know anything beyond the amount of failed transactions, therefore in this PR I'm adding logging of the hashes of the failed txs as well as the exact error message returned by the backend
Testing: I tried submitting a garbled tx and successfully logged the error status as well as an error thrown within the try-catch block with the request to submit tx
> Log failed transactions

- .gitignore
- app/frontend/helpers/wasmLoader.js
- app/tests/src/cardano-wallet.js
- app/yarn.lock
- yarn.lock
1. for tests failing on getTxPlan:
getTxPlan expects just one argument, containing the values for address, coins and donationAmount. The original test code thus didn't provide any of these values and plan generation failed
2. Shelley testnet tests were failing on global leak detection - it seems the global Buffer causing the leaks is not needed (anymore)
3. Wallet import tests seem to be working fine
closes #623
> Fix Byron tests

- server/statsPageRedis.js
Adds a table of contents to Redis stats page along with link to this table of contents from sections of the stats. I made this very simple as is the rest of the page, so open to suggestions.
> Add simple table of contents to redis stats

- server/index.js
- yarn.lock
* Fixes SSL record too long when trying to run adalite locally on https://localhost:3000
* I also ran `yarn install` which probably due to some previous misconfiguration reintroduced the missing `crypto-random-string` dependency (a sub-dependency of release-i, if you run `yarn why`), so this fixes it
> Fix https in dev mode and fix crypto-random-strings dependency

- app/public/css/styles.css
After promoting develop to master I noticed the following UI bug:
I removed the apparently redundant right margin for explorer link - tested both in Shelley and Byron mode
> Fix address explorer link margin

- server/statsPageRedis.js
This PR :
- adds thousands separator to redis stats amounts
- replaces `ul` with `table` and aligns text to the end
- removes unsupported meta atribute
> Add thousands separator to redis stats amounts

- app/frontend/store.ts
- app/tests/src/actions/actions.js
- app/tests/src/actions/wallet-actions.js
- app/tests/src/common/mock.js
- app/tests/src/common/setup-test-config.js
- app/tests/src/index.js
The purpose was to provide a way to test actions.ts (those that contain more logic than setting 1 state field).
In this PR this is only done for loadWallet, other actions will be covered in subsequent PRs.
I had some problems with initializing config, which is needed for both getting initial state and also used across the codebase directly - for that I set up some dummy config on tests startup (as other than actions tests try to load it, though other tests are OK with it remaining null).
> Test for actions.ts

- app/yarn.lock
- package.json
- yarn.lock
Yarn audit was failing with reported low-severity vulnerability of lodash which is blocking the deployment pipeline. This PR fixes it
> Bump lodash

- server/helpers/loadConfig.js
- server/middlewares/statsRedis.js
When we transitioned to the unified Shelley-Byron codebase, we forgot to turn back on sent amount tracking which was causing problems with shelley itn.
tested locally using testnet redis storage - it successfully tracked the sent out amount in byron mode
This PR reintroduces that logic based on https://github.com/vacuumlabs/adalite/blob/f8583baaeaea16fa961b1b581d1a664009940f0f/server/middlewares/statsRedis.js#L58
> Reintroduce tracking of sent amount in Byron mode

- .env.example
- app/frontend/actions.ts
- app/frontend/components/pages/delegations/delegatePage.tsx
- app/frontend/state.ts
- app/frontend/wallet/byron/byron-address-provider.ts
- app/frontend/wallet/constants.ts
- app/frontend/wallet/helpers/mnemonicToWalletSecretDef.ts
- app/frontend/wallet/shelley-wallet.ts
- app/frontend/wallet/shelley/helpers/addresses.ts
- app/frontend/wallet/shelley/shelley-address-provider.ts
- app/package.json
- app/tests/src/actions/transaction-actions.js
- app/tests/src/actions/wallet-actions.js
- app/tests/src/shelley.js
- app/yarn.lock
- server/helpers/loadConfig.js
Replaces cardano-crypto.js lib for a new version that is able to pack Shelley mainnet address types. Uses this library to derive Shelley mainnet addresses for a given secret and removes old testnet related logic.
> Shelley mainnet address packing

- app/frontend/components/common/footer.tsx
- app/frontend/components/pages/receiveAda/addressItem.tsx
- app/frontend/components/pages/txHistory/transactionHistory.tsx
Seiza is down and Cardanoexplorer has apparently some routing issues and you cannot go to an address/txid via the url (try e.g. https://explorer.cardano.org/en/transaction/?id=17eaffc77d431d30b60b5630c69cdc02692d6eac93692072975f0dcfad6cb909), you need to type it into the search bar. This is especially awkard for txids as we do not show them in the interface. Meanwhile, adascan is working again so we can switch back to it.
> Switch cardanoexplorer for adascan

- .eslintrc
- app/frontend/components/pages/delegations/stakingHistoryPage.tsx
- app/frontend/wallet/blockchain-explorer.ts
- package.json
- yarn.lock
Motivation: `yarn eslint` command was not working properly with TypeScript definitions imported from other files as it was classifying them as unused vars.
Changes:
* I updated `.eslintrc` with typescript-specific rules to deal with unused vars, retaining the standard `unused-vars` rule for `.js` files.
* Along the way I was forced to switched from `@typescript-eslint/typescript-estree` parser to `@typescript-eslint/parser` as the issue with redundant unused vars warning was otherwise persisting - I'm not sure about the root cause, but the `typescript-estree` parser was also showing a warning thatt the current typescript version is not officially supported, so it may have something to do ith it. Never the less, the current parser seems to behave properly, not throwing redundant errors
* …
> Fix eslint to work with typescript types

- app/frontend/actions.ts
- app/frontend/wallet/constants.ts
- app/frontend/wallet/shelley-wallet.ts
- app/frontend/wallet/shelley/shelley-ledger-crypto-provider.ts
Implements logic for dynamic fee calculation. At first, we try to get the latest slot from out backend and add 3600 slots to it (meaning the ttl for tx is 1 hour) and if the request for some reason fails, we calculate the ttl from the date.
> Set transaction ttl

- app/frontend/components/common/accordion.tsx
- app/frontend/components/common/balance.tsx
- app/frontend/components/common/navbar/navbarAuth.tsx
- app/frontend/components/common/svg.tsx
- app/frontend/components/pages/delegations/delegatePage.tsx
- app/frontend/components/pages/delegations/shelleyBalances.tsx
- app/public/assets/cash-stack.svg
- app/public/assets/cash-stack_active.svg
- app/public/css/styles.css
Changes:
- updated balloon description on Staking Balance, Available Balance
- changed colors on staking page from blue to pink, so it's consistent with the rest of the app
- changed order of balances on staking page
- available balance and rewards are above the line
- staking balance and nonstaking balance are bellow the line (nonstaking balance is hidden if equals to 0)
- this way it also makes sense mathematically
- similarly looking white buttons with grey text/icons are now using `button secondary` class
- withdraw button has an icon now
- refresh button and withdraw buttons are same width
- updated styles to fix black borders around buttons on chrome browser
- renamed some of existing elements to be consistent across pages (like Balance -> Available Balance)
New:
- added `Accordion` …
> Change staking screen descriptions and make UI design more consistent

- app/frontend/components/pages/delegations/shelleyBalances.tsx
- app/frontend/components/pages/login/loginPage.tsx
- app/frontend/components/pages/login/loginPageSidebar.tsx
- app/frontend/components/pages/login/mnemonicAuth.tsx
- app/public/css/styles.css
New:
- add `next reward` bellow `rewards account balance`
Change:
- change mnemonic texts to include 24/27 words mnemonics
> Update ui texts

- app/frontend/wallet/shelley/shelley-ledger-crypto-provider.ts
- app/frontend/wallet/shelley/shelley-trezor-crypto-provider.ts
Problem: Trezor was not passing protocolMagic to the cardanoGetAddress call, resulting in it being None. This was not an issue until now because it negated itself with a bug in trezor-connect resolved here:
Changes:
* add passing of protocolMagic to the cardanoGetAddress call for trezor crypto provider
* refactor the displayAddressForPath call to pass the proper network parameters for both Ledger and Trezor (the nework id was hardcoded to `0` until now even though the crypto provider received the parameter from outside)
Testing/validation: tested address verification in Adalite on localhost for both Ledger and Trezor and works as expected
> Fix passing of network params to displayAddressForPath for hw wallets

- app/frontend/components/common/unexpectedErrorModal.tsx
- app/frontend/helpers/errorsWithHelp.ts
- app/frontend/translations.ts
- app/frontend/walletApp.js
- app/package.json
- app/yarn.lock
- package.json
- server/emailSubmitter.js
- server/helpers/dropSensitiveEventData.js
- server/index.js
- server/middlewares/statsGoogleAnalytics.js
- server/middlewares/statsRedis.js
- server/statsPageRedis.js
- server/transactionSubmitter.js
- yarn.lock
New:
- Updates sentry to the newest version and moves sentry/browser to package.json in the app folder
- Sentry uncaught error capturing on the server side
- Explicit failed tx capturing in sentry
- Name, email and comment added to event tags on client side ( to be able to show these in slack)
FYI: audit errors are fixed in another PR which on this PR will be rebased.
> Server sentry logging

- app/frontend/walletApp.js
Motivation: "XDR encoding failure" is an error that started appearing since FF 83.0 without apparent side-effects and it results in triggering an error modal upon almost all page loads.
more info: https://bugzilla.mozilla.org/show_bug.cgi?id=1678243
and https://github.com/xwiki-labs/cryptpad/issues/636
Changes: This seems to be an error beyond our control. Fortunately, Adalite's functionality does not seem to be impacted by it as I was able to successfully use the wallet and submit a transaction even if the error appeared at page load. So to not spam the users, this PR is adding the error to a list of ignored errors for sentry, hence stopping the error modal triggering.
Testing: I was able to replicate the error modal locally and after applying the fix the error no longer triggered the …
> Ignore XDR encoding failure

- app/package.json
- app/yarn.lock
Motivation: This update is needed in order for the Ledger Cardano app version 2.1.0 to work properly with Adalite, otherwise, as there were breaking changes in internal calls of the signTransaction call, signing of transactions would fail with a validation error on Ledger app's side.
More info on what changed in the latest ledgerjs version here: https://github.com/cardano-foundation/ledgerjs-hw-app-cardano/releases/tag/v2.1.0
Changes:
* bump `@cardano-foundation/ledgerjs-hw-app-cardano` from version 2.0.0 to 2.1.0
Testing: tested manually end-to-end adalite with Ledger app 2.1.0 and 2.0.4 and logging-in/sending txs works as expected
> Update ledgerjs library to latest version (2.1.0)

- app/frontend/actions.ts
- app/frontend/components/pages/login/hardwareAuth.tsx
- app/frontend/translations.ts
- app/frontend/wallet/shelley/shelley-ledger-crypto-provider.ts
- app/package.json
- app/yarn.lock
Motivation: Currently, when the user selects "Connect with WebUSB" this actually may not be true as the logic still falls back to U2F in case of any problem. This potentially makes for a very confusing debugging experience with users that report issues with the (notoriously unreliable) U2F transport, see: https://github.com/vacuumlabs/adalite/issues/775 And generally, it's really confusing to tell users they are connecting via WebUSB only to fall back to a different transport. If they want that "smart" behavior, they can always go through the highlighted default option.
So the aim of this PR is to make the behavior of "Connect with WebUSB" button more intuitive and actually force WebUSB and display whatever goes wrong with it which should naturally lead the users to set up webusb properly …
> Force WebUSB transport with Ledger when selected

- app/frontend/components/pages/login/hardwareAuth.tsx
- app/public/css/styles.css
Motivation: Fix ledger "connect with WebUSB" button and title relative position so it is more naturally spaced respective to the main button above
Before:
After:
> Fix ledger webusb button margin

- server/statsPageRedis.js
Motivation: adalite usage stats page takes a lot of time to load, intermittently timing out. This is most likely due to the amount of entries in Redis (several thousands) and the sequential scan we do on them. Based on this article: https://dzone.com/articles/the-effects-of-redis-scan-on-performance-and-how-k it seems that increasing the batch size from 10 to something bigger should significantly improve the speed of the scan, offsetting the need to migrate to a different solution in the foreseeable future.
Change: force batch size in the sequential scan of redis in the page that renders the usage stats to be 1024 instead of the default value 10.
Testing: I was not able to test the performance conclusively in my local environment as the requests from localhost to redis seem to be …
> Optimize redis stats - change redis scan bulk size from 10 to 1024

- app/frontend/actions.ts
- app/frontend/components/pages/accounts/accountsDashboard.tsx
- app/frontend/state.ts
- app/frontend/wallet/account-manager.ts
- app/frontend/wallet/shelley-wallet.ts
- app/tests/src/common/account-manager-settings.js
- app/tests/src/wallet/account-manager.js
Motivation: Originally when account discovery hit the limit of accounts (30), it failed with AccountExplorationError. This PR fixes this and stops the exploration before hitting the limit.
Changes:
* modify discoverAccounts to stop exploring when maxAccountIndex is hit
* remove the "Explore" tile should the last discovered account be at the limit
* Finally, there is a bug in Trezor that prevents transactions on accounts over 20' from working properly (https://github.com/vacuumlabs/trezor-firmware/issues/43), so there is a hotfix that overrides that limit for Trezor and sets maxAccountIndex to 20
Testing:
* tested manually with Ledger by setting the maxAccountIndex to a lower value to reproduce the situation when the condition triggers, exploration stops as expected
* tested manually with …
> Fix account discovery if max account is used, set max account to 20 for Trezor

- app/frontend/actions.ts
- app/tests/src/actions/actions.js
- app/tests/src/actions/transaction-actions.js
- app/tests/src/actions/wallet-actions.js
- app/tests/src/address-manager.js
- app/tests/src/cardano-wallet-secret-crypto-provider.js
- app/tests/src/common/account-manager-settings.js
- app/tests/src/common/account-settings.js
- app/tests/src/common/address-manager-settings.js
- app/tests/src/common/crypto-provider-settings.js
- app/tests/src/common/mock.js
- app/tests/src/common/tx-plan-settings.js
- app/tests/src/common/wallet-settings.js
- app/tests/src/wallet/account-manager.js
- app/tests/src/wallet/account.js
- app/tests/src/wallet/address-manager.js
Motivation: 
Test for tx planning were not present at all.
Changes:
- refactor tests and refactors settings to objects
- adds tests for calculating fee
- adds tests for getting tx plan and tx plan settings
Gotcha:
- test for calculating fee is divided into three parts, sendAda, delegation and reward withdrawal, all three containing only one test for now and not having tx plan in its settings. Testing the contents of the plan is the responsibility of the account and these tests are supposed to just test if the fee was calculated, an error was thrown or a behavior caused by the success of getting the tx plan.
> Test tx plannig

- app/frontend/actions.ts
- app/frontend/components/pages/advanced/keys.tsx
- app/frontend/helpers/captureBySentry.ts
- app/frontend/helpers/errorsWithHelp.ts
- app/frontend/translations.ts
Motivation: 
- Lot of ledger related errors come to sentry daily, and all we can do is to advice users to try using webUsb or to our trouble shooting guide. 
- If a network error happens during the fee calculation it results in unexpected error since its not cached.
Changes: 
- catch errors when calculating fee
- add translations for general `Error` and modify the `captureBySentry` helper to send also the params into translations so if the for example the `Error` is present in the translations but doest have a translation matching its params it returns undefined thus resulting in the error being considered unexpected.
- add the ledger errors to `errorsWithHelp` so it automatically recommends user to read the troubleshooting guide, and if that doesn't help he can send us the error if he …
> Fix error handling

- app/frontend/actions.ts
- app/frontend/state.ts
- app/frontend/types.ts
- app/frontend/wallet/account.ts
- app/frontend/wallet/blockchain-explorer.ts
- app/frontend/wallet/explorer-types.ts
- app/frontend/wallet/shelley-wallet.ts
Assigns types to data retrieved from BE endpoints. Leaves space for future refactors. Only patches up new typescript errors due to inconsistency of the state, however, such changes and refactors are out of scope of this PR.
Possible changes:
- WHERE (which file) to store the new types
- Split up purely BE types and any follow-up types of stuff created freshly on FE
> Type blockchain explorer

- app/frontend/components/pages/delegations/stakingHistoryPage.tsx
- app/frontend/wallet/blockchain-explorer.ts
- app/frontend/wallet/explorer-types.ts
- Adds rewards types - ITN, TREASURY, REGULAR. Shows different titles for each of them.
- Removes "UNKNOWN-POOL" for ITN and TREASURY rewards, since they're not bound to any pool.
> Add treasury rewards logic and reward types

- app/frontend/actions.ts
- app/frontend/wallet/account.ts
- app/frontend/wallet/blockchain-explorer.ts
Changes: 
Removes unnessary calls to poolInfo and uses it only as a fallback
When exploring accounts, only external addresses are checked 
Gotcha: 
These are just hot fixed so we dont send so many requests to poolMeta, (which can slow the page a lot). Since both @xdzurman and @DavidTranDucVL  are working on blockchain explorer I didnt try to refactor any of the current behavior and left it for their PRs.
> Optimilize-account-info

- app/frontend/actions.ts
- app/frontend/components/pages/sendAda/donationButtons.tsx
- app/frontend/components/pages/sendAda/sendAdaPage.tsx
- app/frontend/helpers/validators.ts
- app/frontend/state.ts
- app/frontend/types.ts
- app/frontend/wallet/account.ts
- app/frontend/wallet/address-manager.ts
- app/frontend/wallet/blockchain-explorer.ts
- app/tests/src/common/tx-settings.js
- app/tests/src/wallet/account.js
Changes: 
- Adds a simple tests for tx building just so we can refactor the tx building more safely
- Reorder state entries into groups so there are easier to track and work with
- Types sendAda, sendAmount and adds enum for tx plan type
> Refactor transaction building 1

- app/frontend/wallet/account.ts
Changes:
- Check only for 20 addresses when discovering accounts
Motivation: 
- Previously we discovered all addresses and then called `isSomeAddressUsed` with all of them. So if a user had 60 used addresses we passed all of them to the endpoint even tho it allows only 50.
- the bug was "introduced" in commit https://github.com/vacuumlabs/adalite/commit/5c7232def7427d4cde727320d89000a745f7793a where discovery of internal addresses was dropped and there are generally fewer internal addresses as Adalite currently reuses them.
closes #838
> Fix account discovery

- app/frontend/actions.ts
- app/frontend/components/common/viewPort.tsx
- app/frontend/components/pages/dashboard/dashboardPage.tsx
- app/frontend/components/pages/login/loginPage.tsx
- app/frontend/components/pages/login/loginPageSidebar.tsx
- app/frontend/constants.ts
- app/frontend/helpers/assertUnreachable.ts
- app/frontend/state.ts
- app/frontend/types.ts
- Converts loginPage and and loginPageSidebar from classes to components with hooks
- Removes now unnecessary ENABLE_HW_WALLETS constant
- Introduces types
- Renames misleading variables
- Uses useViewport to render components depending on the screen size instead of hiding desktop/mobile components
- Solves mobile bug of HW wallets login not having padding
- Prepares ground for private key login
> Refactor login page and its sidebar

- app/frontend/wallet/blockchain-explorer.ts
- app/frontend/wallet/explorer-types.ts
Motivation: A user reported running into a `Cannot read property 'url' of undefined` error due to given pool not being among the "valid stake pools"
Changes:
* fix the logic fetching pool info to gracefully fall back to `UNKNOWN_POOL_NAME` if pool URL is missing
Testing:
* I was not able to reproduce the exact error, but I tested the wallet loads fine and given logic is triggered by logging from the respective function
> Fix "Cannot read property 'url'" for pools missing from validStakepools mapping

- app/package.json
- app/yarn.lock
- package.json
Motivation: optional chaining was not working in the codebase. Turned out that prettier-eslint was taking the wrong version of prettier in the app directory - it was mirroring a recursive dependency of fetch-mock (prettier version 1.13) which did not support that operation which resulted in the error:
```
prettier-eslint-cli [ERROR]: There was an error formatting "app/frontend/wallet/account.ts": 
SyntaxError: Expression expected. (193:17)
191 | }: AccountParams) => {
192 |   const x = null
> 193 |   console.log(x?.dsfd?.sdf)
|                 ^
194 | 
195 |   const {
196 |     getMaxDonationAmount: _getMaxDonationAmount,
at e (/home/rafael/workplace/cardano/adalite/app/node_modules/prettier/parser-typescript.js:1:267)
at Object.parse …
```
> Fix mirroring of wrong version of prettier dependency in app dir

- app/frontend/helpers/errorsWithHelp.ts
- app/frontend/translations.ts
Motivation: Users are frequently reporting on Sentry NotFoundError and AbortError which after troubleshooting consistently turns out to be due to interference from Ledger Live (though I wasn't able to replicate it myself even on Windows).
Changes: add handling of the aformenetioned errors and update the troubleshooting suggestion for Ledger to explicitly instruct users to close Ledger Live
Testing:
* Adalite loads without problems locally, will see the effect upon deploying to production - given that those are just additions to an existing mapping and the handling logic still allows for sending the error to sentry, this should not have any negative impact
closes #856
> Add handling of common Ledger errors, instruct to turn off ledger live

- app/frontend/types.ts
- app/frontend/wallet/shelley-wallet.ts
- app/frontend/wallet/shelley/shelley-js-crypto-provider.ts
- app/frontend/wallet/shelley/shelley-ledger-crypto-provider.ts
- app/frontend/wallet/shelley/shelley-trezor-crypto-provider.ts
- server/helpers/parseTxBody.js
- server/middlewares/statsGoogleAnalytics.js
Changes:
- adds tracking of crypto provider version when submitting transaction
- for mnemonic it tracks derivationScheme version
- fixes zero output transactions in refis stats
> Track crypto provider versions

- app/frontend/components/common/asset.tsx
- app/frontend/components/common/linkIcon.tsx
- app/frontend/components/pages/dashboard/dashboardPage.tsx
- app/frontend/components/pages/delegations/common.tsx
- app/frontend/components/pages/sendAda/multiAssetsPage.tsx
- app/frontend/components/pages/sendAda/sendAdaPage.tsx
- app/frontend/components/pages/txHistory/transactionHistory.tsx
- app/public/css/0-767px.css
- app/public/css/styles.css
* Display "multi-assets" data from "sendAdaPage" in a standalone card & make it scrollable
* Adjust for all resolutions
* Create `FormattedAssetItem` for shared Asset formatting, with the freedom to use in any layout
// desktop
// mobile
> Create multi assets page

- app/frontend/actions.ts
- app/frontend/components/pages/accounts/accountTile.tsx
- app/frontend/components/pages/accounts/accountsDashboard.tsx
- app/frontend/components/pages/dashboard/dashboardPage.tsx
- app/frontend/components/pages/delegations/currentDelegationPage.tsx
- app/frontend/components/pages/delegations/delegatePage.tsx
- app/frontend/components/pages/delegations/deregisterStakeKey.tsx
- app/frontend/components/pages/delegations/stakingHistoryPage.tsx
- app/frontend/components/pages/sendAda/confirmTransactionDialog.tsx
- app/frontend/components/pages/sendAda/sendAdaPage.tsx
- app/frontend/selectors.ts
- app/frontend/types.ts
- app/frontend/wallet/blockchain-explorer.ts
- app/frontend/wallet/shelley/shelley-transaction-planner.ts
- app/public/css/styles.css
* Add deregister stake key option
* Refactor modals to be only "centralized" in a single place (due to showing transaction modal from "advanced" tab, though it was finally decided not to be used from there, I still find the refactor useful)
* Texts & visuals of confirmation dialog are inspired by Yoroi
* I tried to divide it into more commits to make it easier to follow
Help wanted in: :pray: 
1. Are there some other dialogs that I might be not aware of and could get broken with this refactor? I tested "transfer/delegate" from accounts screen and those worked fine for me
> Staking key deregister

- app/frontend/actions.ts
- app/frontend/components/pages/accounts/accountsDashboard.tsx
- app/frontend/components/pages/dashboard/dashboardPage.tsx
- app/frontend/components/pages/delegations/delegatePage.tsx
- app/frontend/selectors.ts
- app/frontend/state.ts
**Keys removed from global state**
-> totalWalletBalance
-> totalRewardsBalance
Due to the above refactor those further changes were needed:
-> `isBigDelegator` key was removed and  selector introduced
-> `shouldShowPremiumBanner` was reworked
**shouldShowPremiumBanner**
-> localStorage key renamed to `seenPremiumBanner` as otherwise initial value of `shouldShowPremiumBanner`
is misleading (it could be `true` even though we later override it `false` due to not enough funds)
-> by naming it `seenPremiumBanner` it only focuses on whether the user saw it, and whether to display banner
is decided by the selector
**other notes**
* no "memoization" as for now selectors do not perform any "complex" computations
* what do you think about "selector" postfix? Do you find it redundant or like that …
> Remove balances from global state

- app/frontend/actions.ts
- app/frontend/actions/error.ts
- app/frontend/actions/loading.ts
- app/frontend/actions/wallet.ts
- app/frontend/state.ts
Idea for the future is:
-> have multiple "Actions" files
-> later move "actions.ts" into "actions" folder and rename it to "index.ts"
-> if there would be some cyclic-dependencies, extract such "functions/actions" into "actions/common.ts"
-> make all "actions" receive "state" as first object
-> avoid using "setState" outside the "actions"
-> actions can use other actions if not causing cycling deps, e.g. wallet uses "loading/error" actions
-> actions should receive "state" object as first param and optional params object as second param (e.g. error case)
I wanted to avoid more changes in this PR not to grow to big.
**Please pay attention to**
I removed "config/extra" params from loading/error as I believe this is "hacky" pattern and those actions/functions should not have such …
> Divide actions part 1

- server/helpers/loadConfig.js
- server/middlewares/redirectToBaseUrl.js
- server/middlewares/statsGoogleAnalytics.js
- server/middlewares/statsRedis.js
- server/transactionSubmitter.js
* After this is merged, all newly created PRs will have automatically created environments
* If you want to use it for already opened PR, then rebase & reopen them
For testnet CORS were allowed for `https://adalite-*.herokuapp.com`.
> Avoid redirect for review apps

- .circleci/config.yml
- app/frontend/actions.ts
- app/frontend/actions/error.ts
- app/frontend/actions/loading.ts
- app/frontend/actions/wallet.ts
- app/frontend/state.ts
Related to https://github.com/vacuumlabs/adalite/issues/919
- Broke out single job into four separate jobs (`build`, `audit`, `test`, `lint`)
- `build` job fans out to `test` and `lint` and restores install in build from cache
- `audit` runs in parallel to `build` and fails on the first yarn audit that errors
> Separate CircleCI into separate jobs

- app/frontend/wallet/shelley/shelley-transaction-planner.ts
- app/tests/src/index.js
- app/tests/src/tokenBundle.js
I realized that in case there are same assetNames under a different policyId, the function for calculating min ada for output would consider only one unique assetName, which is true but since they are under different policyId they cause the output to be bigger. For this reason we need to calculate unique number of (policyId, assetName) pairs intead.
> Fix counting number of distinct assetNames

- .circleci/config.yml
Based on https://github.com/vacuumlabs/adalite/pull/921
Motivation:
* allow for parallel execution of otherwise independent jobs in the pipeline
Changes respective to https://github.com/vacuumlabs/adalite/pull/921 :
* incorporate Cypress tests
* move restoring of cache/dependencies setup to a reusable command (source: https://preventdirectaccess.com/reuse-steps-circleci/), avoid reliance on cache in individual jobs so they are runnable locally
* extract default setup (docker image) into a "defaults" anchor" (source: https://circleci.com/blog/circleci-hacks-reuse-yaml-in-your-circleci-config-with-yaml/)
Jobs now run in parallel, check CI logs in PR
closes: #919
> Break out CI config into seperate jobs

- app/frontend/actions.ts
- app/frontend/actions/wallet.ts
- app/frontend/components/pages/dashboard/dashboardPage.tsx
- app/frontend/selectors.ts
- app/frontend/state.ts
A mini PR which removes shouldShowExportOption. I'd continue with other keys but then I remembered I was meant to refactor just the "form" global state
> Remove shouldShowExportOption from global state

- app/package.json
- app/yarn.lock
Motivation: We need to update to ssri >= 8.0.1 as reported by dependabot but it is a recursive dependency of webpack which is currently at version 4 and the latest minor version of webpack 4 (https://www.npmjs.com/package/webpack/v/4.46.0) uses ssri ^6.0.1 which is not enough and doesn't allow an automatic update of the dependency.
The suggested solution is to force ssri 8.0.1 over the previously used version 5.3.0, from the changelog: https://github.com/npm/ssri/blob/latest/CHANGELOG.md it seems that only new calls/bugfixes/error throwing behavior has been added, so as long as anything during compilation/runtime doesn't crash it should be fine.
However, we should consider updating to webpack version 5, which seems to make sense alongside the introduction of hot reloading which would …
> Force updated version of ssri recursive dependency

- app/frontend/state.ts
- app/frontend/types.ts
- app/frontend/wallet/backend-types.ts
- app/frontend/wallet/blockchain-explorer.ts
- app/tests/src/common/mock.js
testable with changing
const url = `${ADALITE_CONFIG.ADALITE_BLOCKCHAIN_EXPLORER_URL}/api/account/poolRecommendation/poolHash/${poolHash}/stake/${stakeAmount}`
to e.g.
const url = `${ADALITE_CONFIG.ADALITE_BLOCKCHAIN_EXPLORER_URL}/api/account/poolRecommendation/poolHash/${poolHash}/stake/25000000000000`
and with staging explorer
For accounts with >=25M, recommend a private pool, handled by BE
> Extend pool recommendation API

- app/cypress/support/index.ts
- app/cypress/tsconfig.json
- server/mocking.js
- Implements rather a very simple caching of request for cypress,
(open to suggestions on the hash function or the approach)
the alternative would be to create create a separate command that runs the tests and creates fixtures for the tests, tho this would require a bit more work and I doubt it would speed the testing process up.
- Lowers the sleep time when mocking requests. 
Improved integration tests duration, previously ~4:30 now ~3:00 
Gotcha: 
- let me know if the previous sleep durations had some special purpose other than mimicking the real response time, if we still consider this useful I can create a .env variable on which would the sleep time depend, and set it to 0 for cypres. IMO we dont need the mimicking of real response time anywhere.
> Cache backend for cypress and lower sleep time for tx submit mock

- app/frontend/components/pages/delegations/delegatePage.tsx
- app/frontend/helpers/connect.ts
Current `useActions` is not memoized which means that every re-render of a component that uses it creates whole new actions. This leads to infinite cycle when actions are used as dependencies in `useEffect`.
With this change component should get new actions only once when it uses `useActions`, however every component that uses `useActions` still gets new actions object (I will also try to improve that, maybe in another PR)
This would need some testing of the core functionality whether nothing got broken (but I guess that cypress tests could do it :partying_face: )
> Memoized useActions

- app/frontend/actions/common.ts
- app/frontend/actions/delegate.ts
- app/frontend/actions/poolOwner.ts
- app/frontend/actions/send.ts
- app/frontend/actions/transaction.ts
- app/frontend/components/pages/delegations/delegatePage.tsx
- app/frontend/components/pages/delegations/deregisterStakeKey.tsx
- app/frontend/components/pages/sendAda/confirmTransactionDialog.tsx
- app/frontend/components/pages/sendAda/sendAdaPage.tsx
- app/frontend/state.ts
- app/frontend/types.ts
* cache txPlan per TxType to avoid race-conditions
* require explicit params for "confirm" and "submitTransaction"
* keep backward functionality ("old" prefixes) for parts that were
not updated yet
* remove unnecessary race-condition check from deregister staking screen
This one is copy of https://github.com/vacuumlabs/adalite/pull/917, but due to changes in `actions.ts` it was easier to create new PR. I will close original PR and delete its branch once this is merged.
> Refactor caching of transaction plans

- webpack.build.config.js
The problem is that you can not apply CSS styles in any order otherwise it resolves in a very strange behavior during development.
I decided to remove the "glob" as the sorted order is not good enough for us (it needs to be specific) and we do not change screen resolutions that often. If we start using CSS-modules we would eventually drop those files completely.
The problem occurs only during development, in the production build the styles are applied correctly.
> Fix incorrect styles order in development

- app/frontend/actions/common.ts
- app/frontend/actions/delegate.ts
- app/frontend/wallet/account.ts
- app/frontend/wallet/shelley/helpers/stakepoolRegistrationUtils.ts
- app/frontend/wallet/shelley/shelley-transaction-planner.ts
- app/tests/src/common/tx-settings.js
- app/tests/src/index.js
- app/tests/src/transaction-planner.js
Previously:
- tx plan computation was in a really ugly for cycle
- in case wallet has for example a two utxos 2 ADA and 5 ADA, there was a 50% chance that the 2 ADA utxo gets to the tx plan computation first and if user wanted to send 1.1 ADA, 0.9 would be added to the fee (since its too small for change output) 
- if a wallet didn't have registered staking key, and had less then amount 2ADA balance, no error was shown
Changes: 
- tx plan computation refactored into recursion
- we try to add the change to the fee only if the plan computation with all utxos failed
- error is shown didn't have registered staking key, and had less then amount 2ADA balance
> Refactor tx plan computation into recursive

- app/frontend/errors/unexpectedErrorReason.ts
- app/frontend/wallet/constants.ts
- app/frontend/wallet/helpers/CachedDeriveXpubFactory.ts
Motivation: 
- for wallets that have a lot of account ist more convenient to export public key by batches bigger than 5
Changes: 
- public keys are exported in batches of 5, 10, 20, 20.... (from 20 the batch stays the same, exporting more than 20 key from ledger takes a bit too long)
> Bulk export gradually more public keys

- app/frontend/wallet/shelley/shelley-transaction-planner.ts
Motivation: 
- previously we were checking only outputs without change for max utxo size :facepalm: 
Changes: 
- we check also change for max utxo size
Gotcha: 
- ideally we would create multiple outputs for transactions containing too many tokens but that would require significantly more work, I suggest we address it separately, since this anyway effect small minority of users.
> Check max utxo size also for change

- app/frontend/actions/common.ts
- server/transactionSubmitter.js
Gotcha: we should really do the second part of the error handling refactor, I recommend we do this in a separate issue and have this merged as soon as possible to avoid more sentry errors.
Fixes:
1. Sometimes the error returned by the server is not a JSON but a HTML which then caused error response parsing to fail with `Unexpected token < in JSON at position 0` - for the sake of error logging we may as well pass the response directly to sentry
2. If a user happened to be logged into adalite during an epoch boundary and trying to compute a tx plan, they would get a sentry modal instead of a standard error modal - the custom EpochBoundaryUnderway error was missing from the logic that catches "known" exceptions to display a proper error modal
> Hotfix epoch boundary error catching

- app/frontend/errors/errorMessages.ts
- app/frontend/errors/errorsWithHelp.ts
This error seems to happen for some MacOS users with Ledger (supposedly on webhid transport) and now they are getting a general error modal. This PR improves the UX to show them a proper troubleshooting suggestion
> Handle "NotAllowedError: Failed to open the device." for Ledger in MacOS

- app/frontend/wallet/shelley/helpers/stakepoolRegistrationUtils.ts
- app/frontend/wallet/shelley/transaction/computeTxPlan.ts
- app/tests/src/common/pool-reg-tx-settings.js
- app/tests/src/wallet/account.js
Motivation: 
- refactoring of tx plan computing and splitting change outputs introduces a bud in pool registration, change was assigned null instead of `[]`
Changes:
- fix bug with change
- add tests for pool registration so we don't forget to change plan-computing logic there as well
Fixes: 
https://github.com/vacuumlabs/adalite/issues/1046
> Fix change when registering pool and add tests

- app/frontend/wallet/shelley/shelley-ledger-crypto-provider.ts
- app/package.json
- app/yarn.lock
Tested pool registration with Ledger Cardano app 2.4.1 and 2.3.2 - both work fine. Current master is failing for the newer version as it has an outdated version of ledgerjs
Tested tx submission/delegation as well and work as expected too
> Bump ledgerjs to support pool registration with ledger app 2.4.1

- app/frontend/actions/wallet.ts
- app/frontend/helpers/getConversionRates.ts
- app/frontend/state.ts
- app/frontend/tokenRegistry/tokenRegistry.ts
- app/frontend/types.ts
- server/helpers/cache.js
- server/helpers/chunk.js
- server/tokenRegistryProxy.js
Changes
- Load token metadata in non-blocking matter. After wallet is loaded we would show tokens without linked metadata until the request fetches data from remote service and then update UI accordingly.
- Change request to token registry to bulk request.
- Maximum amount of tokens per request arbitrarily set to 100.
- Cache entries on level of token metadata, instead of functions calls.
- Set maximum limit for wallet for which we support token metadata, currently set arbitrary to 2000.
> Optimize token registry metadata processing

- app/frontend/actions/transaction.ts
- app/frontend/components/common/modal.tsx
- app/frontend/components/pages/sendAda/confirmTransactionDialog.tsx
- app/frontend/components/pages/voting/transactionPage.tsx
- app/frontend/components/pages/voting/votingDialog.tsx
As the submit tx UI has been updated to be non-blocking, we probably forgot to update the catalyst registration screen, which now shows to the user the "Confirm transaction" button as non-disabled while the previously confirmed tx is being submitted, which can lead to unpredictable behavior.
This PR is fixing the issue above and disables the button while the wallet is not ready to submit further txs
Other fixes:
* disable closing of the tx confirmation modal if user clicks outside by introducing a configurable property of the common modal element
* if user rejected the transaction while signing, UI got stuck on waiting for ledger - apparently `stopLoadingAction` call was missing in the "finally" block of the tx signing/submission handler
It can be tested with "odor match ..." mnemonic or …
> Disable tx creation while catalyst registration is being submitted

- server/helpers/getRequestIp.js
- server/index.js
- server/middlewares/statsGoogleAnalytics.js
- server/middlewares/statsRedis.js
Since we setup an application firewall, it appends its IPs to the "fwd" header, skewing our metrics based around IP addresses. This PR fixes the call to take only the first IP (the on of the client itself) from the respective header
More context: https://serverfault.com/questions/846489/can-x-forwarded-for-contain-multiple-ips
Testing: included temporary logging to see in logs if ips are being extracted properly once deployed, is to be reverted afterwards
> Refactor IP extraction to account for firewall

- app/public/js/init.js
- server/helpers/loadConfig.js
- server/index.js
Ensures that users get latest js as soon as we make a new release of the app. A bit hacky, but given the effort it would take to rework serving the initial page (injecting the content hashes into HTML, meaning it would have to be done by webpack or keep it in expresses but with even uglier hacks) I think it's a reasonable workaround and at least I tried to clarify the rationale with comments
> Invalidate browser cache after new version release

- server/index.js
Motivation: Make sure users request the latest HTML of the initial page which in turn loads the latest js/css assets, otherwise, after releasing the app some users may still keep the cached versions of the assets, resulting in seeing an outdated version of the website
Inspired by https://stackoverflow.com/a/53240717/2657249
Testing: checked that the respective header is set when fetching the page and the main HTML appears to no longer be cached, even after repeated refreshing
> Enforce non-caching of the initial landing page HTML

- app/frontend/components/common/asset.tsx
- app/frontend/tokenRegistry/tokenRegistry.ts
- app/frontend/types.ts
Currently, we display asset name that is on-chain. In metadata, name field is mandatory. For tokens that actually have metadata, it makes sense to display metadata name to user instead.
> Display metadata token name instead of onchain asset name

- app/public/css/0-1366px.css
- app/public/css/styles.css
The css that makes the footer sticky currently has a max height of 1366px so it doesn't get applied on large screens.
I removed this so that the css is applied on all screen sizes as a base that can be overridden on smaller screens.
Fixes #1086 
- I've found it very helpful to use storybooks with visual regression snapshots to understand the effects of css changes
> Apply sticky footer CSS outside of media query

- .circleci/config.yml
- .eslintrc
- app/frontend/helpers/dataProviders/stakepoolDataProvider.ts
- app/frontend/helpers/dataProviders/types.ts
- app/frontend/wallet/blockchain-explorer.ts
- app/package.json
- app/yarn.lock
- package.json
- yarn.lock
Motivation: fix potentially undefined pool info (possibly for some pool that has been unregistered). We've got reports by users with the following breadcrumbs:
```javascript
const getPool = async (poolHash: string): Promise<StakePoolInfo | HostedPoolMetadata> => {
const stakePool = validStakepoolDataProvider.getPoolInfoByPoolHash(poolHash)
if (stakePool?.name) {
return stakePool
}
const poolInfo = await getPoolInfo(stakePool.url)
```
and error: `Cannot read properties of undefined (reading 'url')` (Chrome) or `stakePool is undefined` (Firefox)
Changes: fix signature of getPoolInfoByPoolHash/Ticker to "acknowledge" it may return also null and the typescipt naturally warns in places where this breaks the assumption the data is always defined, which turned out to be only the place where this …
> Handle undefined pool info

- package.json
- yarn.lock
Bump version of universal analytics to the one that has fixed a bug that cause requests to fail: https://github.com/peaksandpies/universal-analytics/commit/2d3dd2ff479e021770f5488788b31ae2f6364b06
This is apparently polluting our sentry logs. I was able to replicate it locally and the problem disappeared after updating the lib
> Release 6.8.11

- app/frontend/wallet/constants.ts
Fixes bug that prevents users from logging into Adalite because Trezor didn't have a fallback value for feature checks which had been recently refactored to fall back to check for `MINIMAL` version if the feature queried isn't available, and Trezor didn't have such value set, causing the check to crash
> Add fallback value for Trezor crypto provider feature checks

- app/frontend/errors/errorMessages.ts
Motivation: The original wording was gramatically incorrect and it didn't give to the users clear guidance on what to do to solve the problem
> Improve wording of tx too big error

- server/middlewares/csp.js
Improve content security policy to comply with https://cspscanner.com except `upgrade-insecure-requests` which is needed to make Bitbox02 work on Firefox as it requires a locally hosted bridge app to interact with it as an alternative to webhid which isn't supported in FF
CSP settings can be verified at: https://cspscanner.com/?q=https%3A%2F%2Fadalite-improve-csp-ypgfvkargw.herokuapp.com%2F
testing of potentially impacted functionality:
tested on the review app in this PR, except BitBox02 which needs to be tested locally due to origin whitelisting by the bridge app (which whitelists only adalite.io and localhost)
> Improve CSP

- app/frontend/components/pages/txHistory/transactionHistory.tsx
Until now, we didn't include token transfers in CSV export, this PR adds them.
Examples (Ledger mnemonic with tokens - Mainnet):
New: [transactions_new.csv](https://github.com/vacuumlabs/adalite/files/7845725/transactions_new.csv)
Old: [transactions_old.csv](https://github.com/vacuumlabs/adalite/files/7845726/transactions_old.csv)
> Add tokens to csv export

- app/package.json
- app/yarn.lock
- yarn.lock
WebHID access to the BitBox02 stopped working as of Chrome version
97 due to incorrect vendor/product filter names. See also:
https://github.com/digitalbitbox/bitbox02-api-js/pull/62
Simply upgrading the package solves the problem.
> bitbox02: update bitbox02-api-js to v0.12.0, fixing WebHID in Chrome

- app/frontend/actions/address.ts
- app/frontend/actions/poolOwner.ts
- app/frontend/actions/transaction.ts
- app/frontend/components/common/addressVerification.tsx
- app/frontend/components/pages/dashboard/walletOperationStatus.tsx
- app/frontend/components/pages/sendAda/confirmTransactionDialog.tsx
- app/frontend/errors/errorMessages.ts
- app/frontend/errors/internalErrorReason.ts
- app/frontend/state.ts
- app/frontend/wallet/blockchain-explorer.ts
- app/frontend/wallet/shelley-wallet.ts
- app/package.json
- app/yarn.lock
- package.json
- server/helpers/fetchWithTimeout.js
- server/poolInfoGetter.js
- yarn.lock
Fixes/improvements:
1. Fix audit errors, clean up resolutions
2. Improve tx submission handling to deal properly with transactions from blockfrost (handling code 425 - mempool full), and changing UI message from "transaction failed" to "transaction error" so it's not misleading if there was an error, but the tx itself didn't necessarily fail
3. Getting pool metadata request may take very long if the metadata endpoint is unresponsive. So far, adalite's endpoint to get that was awaiting indefinitely, needlessly blocking the request and Adalite UI when initially loading the wallet (in prod it would timeout after 30 seconds, since heroku kills the request after such time) - happened for me on testnet for `odor match...` mnemonic
4. Fix to a bug in UI while withdrawing - "address verifying" …
> Improve tx submission handling

- app/bitbox02-api.d.ts
- app/frontend/components/pages/common.tsx
- app/frontend/components/pages/receiveAda/myAddresses.tsx
- app/frontend/components/pages/sendAda/sendAdaPage.tsx
- app/frontend/errors/errorMessages.ts
- app/frontend/wallet/constants.ts
- app/frontend/wallet/shelley/shelley-bitbox02-crypto-provider.ts
- app/package.json
- app/yarn.lock
- package.json
Enable tokens for bitbox02 9.9.0 firmware
Tested with physical device both that for 9.8.0 token transactions fail with the expected error, prompting the user to upgrade (and non-token pass) and for 9.9.0 both transactions pass
> Release 6.9.18

- app/frontend/components/pages/txHistory/transactionHistory.tsx
- app/package.json
- app/yarn.lock
- yarn.lock
Context: wallet load/csv export was failing with an error `Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.` We don't have the exact data to replicate it, the error was reported by a user.
Apparently, this happened because the csv string could contain non-latin characters. This PR migrates to a library which handles these edge cases, see https://stackoverflow.com/a/45725439/2657249
Note: this PR also fixes the yarn audit issue present on current develop (ajv)
How to test: try exporting history as csv and check that it still works as intended
> Fix csv export

- .circleci/config.yml
- .iyarc
- app/.iyarc
- app/package.json
- app/yarn.lock
- package.json
- yarn.lock
rationale: it allows suppressing advisories we can otherwise do nothing reasonable about for the time being. Currently, there's such an issue e.g. with the `minimist` package which this PR suppressed warnings about
> Replace yarn audit with improved-yarn-audit

- app/frontend/wallet/blockchain-explorer.ts
Loading of wallet is slow. The main culprit is bulk address summary fetch, we already cache this request, but the interval in between requests is higher than TTL in the cache. This hotfix should halve loading times.
Next possible steps
- look into the performance of mentioned request
- introduce a more effective loading of accounts (either lazy or in the background)
> Increase bulk addresses summary cache ttl

- app/package.json
- app/yarn.lock
Updating to ledgerjs 5.0.0 library (pre-release) to be ready for new Ledger release with Plutus support
How to test: try performing sending, staking and a catalyst voting registration
> Update to LedgerJS 5.0.0 to prepare for Ledger release

- app/yarn.lock
- package.json
- yarn.lock
How to test:
* try logging into a wallet and check that it works properly
* to test redis, set up the project locally, set REDIS_URL to use the one from adalite-staging heroku app and try loading `/usage_stats` and check that it matches the content on adalite-staging - it will load locally much slower than on staging, this is expected due to making a remote heroku connection
> Fix yarn audit issues

- app/frontend/walletApp.js
- package.json
This unhandled error sometimes, depending on how quickly Adalite managed to load, especially when cached, resulted in Adalite showing an error prompt
https://github.com/ccwalletio/tracker/issues/119
> Ignore Webassembly error triggered by Eternl addon

- app/frontend/components/common/asset.module.scss
- app/frontend/components/common/asset.tsx
- app/frontend/components/pages/advanced/signPoolCertTxModal.tsx
- app/frontend/components/pages/sendAda/confirmTransactionDialog.tsx
- app/frontend/components/pages/sendAda/multiAssetsPage.module.scss
- app/frontend/components/pages/sendAda/multiAssetsPage.tsx
- app/frontend/components/pages/sendAda/sendAdaPage.tsx
- app/frontend/components/pages/txHistory/transactionHistory.tsx
- app/public/css/styles.css
https://vacuum.atlassian.net/browse/ADLT-1180
See the following screenshots. The new version is on the left side, the old version is on the right side.
Previously we have shown:
- `Off-chain asset name + Ticker` or `On-chain name` in the header
- `Policy ID`,  `Fingerprint`, and `Details` in the expanded content.
This had some problems. `On-chain name` can be hard to read and isn't very helpful for the user. Changes:
- Define a new label for tokens, which is always readable. The priority is the following:
- `Icon + off-chain name + ticker` > `Onchain name` (must be human-readable) > `Fingerprint`
- Add all information to the description. This is the same as we do it on NuFi:
- `Name`, `Ticker`, `Policy ID`, `Asset name`, `Fingerprint`
There is one more thing that I find a little bit …
> Improve how we display token information

- .circleci/config.yml
- app/cypress/integration/sendingTab.spec.ts
- app/package.json
- app/yarn.lock
- package.json
- yarn.lock
1. update moment to latest version, remove no longer needed version of the lib from the project root
2. integration tests were failing, turns out somebody sent tokens to the cypress test wallet and the tests weren't able to handle multiple tokens in the wallet, so I fixed it to take the first available token from the list
> Update moment to v 2.29, fix integration tests

- app/frontend/components/pages/delegations/currentDelegationPage.tsx
We forgot to convert pool.liveStake into BigNumber before calling printAda.
> Fix incorrectly called staking screen's printAda call

- app/frontend/actions/delegate.ts
The delegation fee calculation asserted on the selected pool being set which is however not always the case because the selectedPool is reset when clicking between the tabs and the function to calculate the fee is ran denounced, therefore with some delay (300ms) and by that time the pool data in the state may already be reset
> Fix delegation fee calculation crashing while clicking between tabs

- app/frontend/components/app.tsx
- app/frontend/components/common/unexpectedErrorModal.tsx
- app/frontend/components/errorBoundary.tsx
Errors thrown while rendering a component were blocking rendering until now, effectively freezing the app which is very bad UX, plus such errors wouldn't have a chance to reach us without somebody proactively reporting it which defeats the purpose of error tracking.
This PR adds a top-level "ErrorBoundary" component which intercepts any errors during rendering and falls back to the unexpected error modal, and if the error is caught at that level, we tell the error modal to refresh the page after being closed
Try adding some test errors anywhere in the components/actions, like `throw new Error('xxx')` and check that a proper error modal is shown. e.g. an error thrown in router.tsx would previously result in a blank page and now the error modal should be shown.
Note: to be able to see the …
> Add top-level error boundary [ADLT-1518]

- app/frontend/wallet/account.ts
Motivation: there was a Byron address with many token utxos where the user struggled to send an ADA tx because the resulting tx was too big. Turns out our coin selection algorithm was prioritizing "non-staking" utxos regardless of whether they had tokens or not, causing the tx plan to build unnecessarily big txs when trying to send ADA out of such address.
Changes: This PR combines staking and non-staking utxos into a single list before splitting it into the token and ada utxos, adding proper priority even to "non-staking" utxos when sending ADA out of the wallet
How to test: Try sending ADA out of the review app to check tx building still works
> Fix coin selection for Byron addresses with tokens

- app/frontend/components/pages/txHistory/transactionHistory.tsx
- app/frontend/types.ts
- app/frontend/wallet/blockchain-explorer.ts
Adds received from to exports. For now choosing the first non-wallet address.
E.g. motivation: ability to gather all the addresses that would sent donations to a given account.
Extends tx summary with the from/to addresses.
> Export: add from address & txsummary with from/to

- app/frontend/actions/poolOwner.ts
- app/frontend/wallet/account.ts
- app/frontend/wallet/shelley/shelley-bitbox02-crypto-provider.ts
- app/frontend/wallet/shelley/shelley-ledger-crypto-provider.ts
- app/frontend/wallet/shelley/shelley-transaction.ts
- app/frontend/wallet/shelley/shelley-trezor-crypto-provider.ts
- app/frontend/wallet/shelley/types.ts
- app/tests/src/common/tx-settings.ts
Motivation: I have yet to test it, but while testing bitbox02 I realized pool registrations with missing ttl were almost certainly not working. TTL became optional in Mary era: https://github.com/input-output-hk/cardano-ledger/blob/master/eras/shelley-ma/test-suite/cddl-files/shelley-ma.cddl which we already support, but for missing TTL our code would try to generate the TTL, making the tx to be actually signed inconsistent with the tx body supplied
Change: Add proper handling of null TTL so that pool registrations without TTL can work, extend related type signatures and add test case for transaction with null TTL
> Handle optional ttl

- app/frontend/actions/wallet.ts
- app/frontend/components/pages/login/wantedAddressesModal.tsx
- app/frontend/wallet/account.ts
- app/frontend/wallet/blockchain-explorer.ts
- app/frontend/wallet/constants.ts
- yarn.lock
* Add personalized pool saturation message
* update logic to show the message to take into account whether the user already made the changes requestes (i.e. no longer delegating to any of the pools we want to desaturate)
* integrate with new endpoint in adalite BE (needs to be reviewed/deployed first), which allows custom recommendations per stake address (needed to override the recommendations for certain stake addresses that we know are saturating our pools)
> Add pool saturation message [ADLT-2077]

- app/frontend/components/pages/delegations/stakingHistoryPage.tsx
- app/frontend/components/pages/sendAda/multiAssetsPage.module.scss
- app/frontend/components/pages/sendAda/multiAssetsPage.tsx
- app/frontend/components/pages/txHistory/transactionHistory.tsx
- app/frontend/wallet/blockchain-explorer.ts
- app/frontend/wallet/shelley/helpers/addresses.ts
- app/public/css/styles.css
Wallets with many assets (thousands) and very long tx history may currently slow down the wallet UI to the point of being unusable/crashing the website. This PR fixes the issue by limiting the amount of assets/tx history items shown by default to 50 and showing more only if user explicitly clicks on "show more" at the bottom of the trimmed list
Moreover, some backend requests on such big wallets may take several tens of seconds to load which causes unnecessary cache misses in our simplistic time-based cache, because functions depending on such slow queries may cause their fetch multiple times if some of them awaited the result for more than 15s (current cache time). Given we invalidate the cache after transactions and allow that also when user clicks refresh-button, it seems fair enough …
> limit showing long token lists/tx history by default [ADLT-2545]

- app/frontend/components/pages/accounts/accountsDashboard.tsx
- app/frontend/components/pages/delegations/shelleyBalances.tsx
- app/frontend/components/pages/sendAda/confirmTransactionDialog.tsx
- app/frontend/wallet/shelley/transaction/computeTxPlan.ts
- app/frontend/wallet/shelley/transaction/shelley-transaction-planner.ts
- app/tests/src/common/tx-settings.ts
Turns out that in case the user isn't already delegating to a DRep, withdrawals cannot be combined with drep delegation and the tx just fails with `ConwayWdrlNotDelegatedToDRep`. This PR fixes this issue by removing the withdrawal from the withdrawal tx if no drep delegation is detected, and we show a modified tx summary which let's the user know about the edge case and the need to sign an extra tx:
A better UX would obviously be making it a flow where two txs would be submitted automatically, instead of making the user "withdraw" again, but given this is a one-off thing, such extra handling would be imho an overkill
> Fix drep delegation for withdrawals [ADLT-3243]

- app/frontend/components/pages/sendAda/confirmTransactionDialog.tsx
- package.json
- yarn.lock
Withdrawal summary in case of delegation to drep may crash if the transaction happens to have no change outputs. This PR fixes the issue by dropping the address from the summary altogether as it doesn't really make sense there (we don't show source address for pool delegation either)
> Fix withdrawal summary if delegating to DRep
